feat: iOS - Add SwiftPM support section in installing Beagle iOS
ZupIT/beagle-docs pull request #489
Opened 2021-04-20 14:47 UTC by dantes-git

### Related Issues
https://github.com/ZupIT/beagle/pull/1484

### Description
Add SwiftPM support section in installing Beagle iOS doc

2021-04-22 13:39 UTC, luismaximozup submitted a review, later dismissed

2021-04-22 17:27 UTC, theffc commented on content/en/get-started/installing-beagle/ios.md
> +pod 'Beagle', '~> 1.7'
if we specify a hard coded version here, we will need to change that on every release outside the range of this version. And so, to avoid that maintenance, I think it would be better to don't specify it.
This also applies for other places that we are specifying versions (Carthage and SPM)

2021-04-22 17:27 UTC, theffc commented on content/en/get-started/installing-beagle/ios.md
> +Currently, Beagle is available for integrations through [**Carthage**](https://github.com/Carthage/Carthage), [**CocoaPods**](https://cocoapods.org) or [**SwiftPM**](https://swift.org/package-manager
Just changing order so CocoaPods and SPM come first, which are the ones we have used the most and have more confidence.

```suggestion
Currently, Beagle is available for integrations through [**CocoaPods**](https://cocoapods.org), [**SwiftPM**](https://swift.org/package-manager/), or [**Carthage**](https://github.com/Carthage/Carthage).
```

2021-04-22 17:27 UTC, theffc commented on content/pt/get-started/installing-beagle/ios.md
> +Hoje o Beagle está disponível para integração através do [**Carthage**](https://github.com/Carthage/Carthage), [**CocoaPods**](https://cocoapods.org) ou [**SwiftPM**](https://swift.org/package-manage
Just changing order so CocoaPods and SPM come first, which are the ones we have used the most and have more confidence.

```suggestion
Atualmente, o Beagle está disponível para integração através do [**CocoaPods**](https://cocoapods.org), [**SwiftPM**](https://swift.org/package-manager/), ou [**Carthage**](https://github.com/Carthage/Carthage).
```

2021-04-23 12:42 UTC, Tiagoperes requested changes

2021-04-23 12:42 UTC, Tiagoperes commented on content/en/get-started/installing-beagle/ios.md
> +Currently, Beagle is available for integrations through [**Carthage**](https://github.com/Carthage/Carthage), [**CocoaPods**](https://cocoapods.org) or [**SwiftPM**](https://swift.org/package-manager
Also, it should be "and", not "or".

2021-04-23 12:42 UTC, Tiagoperes commented on content/en/get-started/installing-beagle/ios.md
> +We have two ways of configure `Beagle` using SwiftPM:
We have two ways **to** configure

OR

We have two ways of **configuring**

2021-04-23 12:42 UTC, Tiagoperes commented on content/pt/get-started/installing-beagle/ios.md
> +Hoje o Beagle está disponível para integração através do [**Carthage**](https://github.com/Carthage/Carthage), [**CocoaPods**](https://cocoapods.org) ou [**SwiftPM**](https://swift.org/package-manage
Use "e" instead of "ou"

2021-04-23 12:42 UTC, Tiagoperes commented on content/pt/get-started/installing-beagle/ios.md
> +Para integrar o Beagle à sua aplicação através do **Carthage** você precisa adicionar o framework como dependência no seu `Cartfile`.
"Para integrar o Beagle à sua aplicação através do Carthage, você..."

faltou vírgula

2021-04-23 13:12 UTC, dantes-git commented on content/en/get-started/installing-beagle/ios.md
> +pod 'Beagle', '~> 1.7'
In SPM we need to specify the minimum version requirement

2021-04-23 13:20 UTC, hernandazevedozup approved these changes

2021-04-23 13:51 UTC, Tiagoperes approved these changes

2021-04-23 13:51 UTC, merged