move overview to beagle helpers root page
ZupIT/beagle-docs pull request #524
Opened 2021-05-04 18:05 UTC by luismaximozup

2021-05-04 21:17 UTC, matheusribeirozup approved these changes

2021-05-04 21:17 UTC, matheusribeirozup commented
Are you going to open a PR for 1.7 too or just for main?

2021-05-05 13:26 UTC, luismaximozup commented
> Are you going to open a PR for 1.7 too or just for main?

I don't know if it is necessary to have something in 1.7. I think we can bring these tutorials and examples to 1.8

2021-05-10 12:46 UTC, carlossteinzup commented on content/en/get-started/using-beagle-helpers/backend/_index.md
> +  Here, you’ll find all backend libs to help you to use Beagle.
```suggestion
 This section lists all backend libs that will help you to use Beagle.
```

2021-05-10 14:06 UTC, mdcpmoreira reviewed
Review done :)

2021-05-10 14:06 UTC, mdcpmoreira commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +  It is a backend Library that provides a gRPC service allowing your gRPC application to support Beagle Screens.
```suggestion
  In this section, you will find all information related to a backend Library that provides a gRPC service allowing your gRPC application to support Beagle Screens.
```

2021-05-10 14:06 UTC, mdcpmoreira commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- We recommend using lib with springboot or micronaut to facilitate usability. Follow both examples below.
```suggestion
- It is recommended that you use a lib with springboot or micronaut to help on usability. Follow both examples below.
```

2021-05-10 14:06 UTC, mdcpmoreira commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Done! Your application already be available in localhost: - Micronaut: http://localhost:50051/ - Spring Boot: http://localhost:9090/
```suggestion
- Done! Your application will be available in localhost: - Micronaut: http://localhost:50051/ - Spring Boot: http://localhost:9090/
```

2021-05-10 14:06 UTC, mdcpmoreira commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- For this, you need a client to get your service response, we recommended the [BloomRPC](https://github.com/uw-labs/bloomrpc) to simulate a local request on your gRPC API:
```suggestion
- For this, you need a client to get your service response. In this case, it is recommended the [BloomRPC](https://github.com/uw-labs/bloomrpc) to simulate a local request on your gRPC API:
```

2021-05-10 14:06 UTC, mdcpmoreira commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- You can access the lib proto files [here](https://github.com/ZupIT/beagle-helpers/backend/grpc-lib/src/main/proto), you will need them in the bloomRPC client
```suggestion
- You can access the lib proto files [here](https://github.com/ZupIT/beagle-helpers/backend/grpc-lib/src/main/proto) because you will need them in the bloomRPC client.
```

2021-05-10 14:06 UTC, mdcpmoreira commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +#### 👉 This tutorial is available on github with more advanced examples, such as headers and interceptors for example, if you are interested, access them [here](https://github.com/ZupIT/beagle-helper
```suggestion
#### 👉 This tutorial is available on github with more advanced examples, such as headers and interceptors for example. If you are interested, access them here on [backend examples](https://github.com/ZupIT/beagle-helpers/backend/examples)
```

2021-05-10 14:06 UTC, carlossteinzup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Create a class named HomeScreen and extends ScreenBuilder of the beagle framework
```suggestion
- Create a class named HomeScreen and extend it from ScreenBuilder , that is a beagle framework class
```

2021-05-10 14:07 UTC, carlossteinzup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Create another class named SplashScreen and extends ScreenBuilder too.
```suggestion
- Create another class named SplashScreen that extends from ScreenBuilder too.
```

2021-05-10 14:10 UTC, carlossteinzup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Open your terminal and navigate to the root of the created project and run the command:
```suggestion
- Open a terminal and navigate to your new created project root and run the command:
```

2021-05-10 14:11 UTC, carlossteinzup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Done! Your application already be available in localhost: - Micronaut: http://localhost:50051/ - Spring Boot: http://localhost:9090/
```suggestion
- Done! Your application will already be available in localhost: - Micronaut: http://localhost:50051/ - Spring Boot: http://localhost:9090/
```

2021-05-10 14:47 UTC, carlossteinzup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Finally, you can access the Beagle screen payload through the getScreen method of BeagleScreenService endpoint
```suggestion
- Finally, you can access the Beagle screen payload using the getScreen method from the BeagleScreenService
```

2021-05-10 14:48 UTC, carlossteinzup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- For this, you need a client to get your service response, we recommended the [BloomRPC](https://github.com/uw-labs/bloomrpc) to simulate a local request on your gRPC API:
```suggestion
- For this example, you will need a client in order to get your service response. We recommend the [BloomRPC](https://github.com/uw-labs/bloomrpc) to simulate a local request on your gRPC API:
```

2021-05-10 18:17 UTC, luismaximozup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Done! Your application already be available in localhost: - Micronaut: http://localhost:50051/ - Spring Boot: http://localhost:9090/
```suggestion
- Done! Your application will already be available in localhost: - Micronaut: http://localhost:50051/ - Spring Boot: http://localhost:9090/
```

2021-05-11 18:34 UTC, carlossteinzup submitted a review, later dismissed

2021-05-13 20:28 UTC, igorgiumellizup requested changes

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +gRPC is a new and fast growing technology to communicate different systems through a network connection. It's based on
```suggestion
gRPC is a new and fast growing technology that allows different systems to communicate through a network connection. It's based on
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +gRPC service that makes it possible to register your screens and a method that returns them to a gRPC client.
```suggestion
gRPC service that makes it possible to register your screens, and a method that returns them to a gRPC client.
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- It is recommended that you use a lib with springboot or micronaut to help on usability. Follow both examples below.
```suggestion
- It is recommended that you use a lib with Spring Boot or Micronaut to help on usability. Follow both examples below.
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- You can access [spring website here](https://start.spring.io) and generate a zip project with the basic settings already configured.
```suggestion
- You can access [Spring Boot website here](https://start.spring.io) and generate a zip project with the basic settings already configured.
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +#### Use spring project generator
```suggestion
#### Using Spring Boot project generator
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +#### Use micronaut project generator
```suggestion
#### Using Micronaut project generator
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- You can access [micronaut website here](https://micronaut.io/launch/) and generate a zip project with the basic settings already configured
```suggestion
- You can access [Micronaut website here](https://micronaut.io/launch/) and generate a zip project with the basic settings already configured
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Now, you can extract zip folder generated, and open with your favorite IDE. We recomended Intellij Community.
```suggestion
- Open the extracted folder in your favorite IDE. We recommend Intellij Community.
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Open the gradle.build file (or pom.xml if you choose maven) in your project root and add the Beagle gRPC library
```suggestion
- Open the gradle.build file (or pom.xml if you choose Maven) in your project root and add the Beagle gRPC library
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Create a class named HomeScreen and extend it from ScreenBuilder , that is a beagle framework class
```suggestion
- Create a class named HomeScreen and extend it from ScreenBuilder, that is a Beagle framework class
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +#### Using Beagle grpc lib
```suggestion
#### Using Beagle gRPC lib
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Open a terminal and navigate to your new created project root and run the command:
```suggestion
- Open a terminal, navigate to the new created project root and run the command:
```

2021-05-13 20:28 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/overview.md
> +If you wish to use Beagle for an application in production we advise you to [configure a project
```suggestion
If you wish to use Beagle for an application in production, we advise you to [configure a project
```

2021-05-13 20:29 UTC, igorgiumellizup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +#### Windows System
No Linux / macOS section?

2021-05-17 14:03 UTC, luismaximozup commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +#### Windows System
This PR is still in draft, soon to be concluded

2021-05-17 20:45 UTC, LG95 commented on content/en/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +gRPC service that makes it possible to register your screens, and a method that returns them to a gRPC client.
```suggestion
## How Beagle gRPC works?

This library allows you to create Beagle BFFs serving screens through gRPC. It acts as a translator, converting Beagle JSONs to protocol buffer messages. The lib provides an abstraction that implements a gRPC service that makes it possible to register your screens, and a method that returns them to a gRPC client.
```

2021-05-18 12:09 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +## Como gRPC funciona?
```suggestion
## Como o Beagle gRPC funciona?
```

2021-05-18 12:22 UTC, igorgiumellizup requested changes

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +em protocol buffer, permitindo que seu BFF se conecte a qualquer aplicações gRPC. A lib fornece uma abstração que implementa um
```suggestion
em protocol buffer, permitindo que seu BFF se conecte a qualquer aplicação gRPC. A lib fornece uma abstração que implementa um
```

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +serviço gRPC possibilitando o registro de suas telas através de um método, além disso, as retorna desserializadas para um cliente gRPC.
```suggestion
serviço gRPC possibilitando o registro de suas telas através de um método, e, além disso, as retorna desserializadas para um cliente gRPC.
```

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- É recomendado que utilize os frameworks do spring boot e micronaut para facilitar a usabilidade da bibloteca.
```suggestion
- É recomendado que utilize os frameworks do Spring boot e Micronaut para facilitar a usabilidade da bibloteca.
```

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +#### Gerando um projeto spring boot
```suggestion
#### Gerando um projeto Spring Boot
```

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Você pode acessar o [website do spring boot](https://start.spring.io) e gerar um arquivo zip do projeto com as configurações basicas definidas por padrão.
```suggestion
- Você pode acessar o [website do Spring Boot](https://start.spring.io) e gerar um arquivo zip do projeto com as configurações básicas definidas por padrão.
```

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +#### Gerando um projeto com micronaut
```suggestion
#### Gerando um projeto com Micronaut
```

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Voce pode acessar o [website do micronaut](https://micronaut.io/launch/) e gerar um arquivo zip do projeto com as configurações básicas definidas por padrão
```suggestion
- Voce pode acessar o [website do Micronaut](https://micronaut.io/launch/) e gerar um arquivo zip do projeto com as configurações básicas definidas por padrão
```

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Crie uma classe chamada HomeScreen e extenda-a de ScreenBuilder, que é uma das abstração para contrução de telas fornecida pelo Beagle framework
```suggestion
- Crie uma classe chamada HomeScreen, estendendo de ScreenBuilder, que é uma das abstrações para a construção de telas fornecidas pelo Beagle framework
```

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Crie outra classe chamada SplashScreen que também extende de ScreenBuilder.
```suggestion
- Crie outra classe chamada SplashScreen que também estende de ScreenBuilder.
```

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +- Para este exemplo, você precisará de um cliente para obter a resposta do serviço. Recomendamos o [BloomRPC](https://github.com/uw-labs/bloomrpc) para simular uma solicitação local em sua API gRPC:
```suggestion
- Para este exemplo, você precisará de um cliente para obter a resposta do serviço. Recomendamos o [BloomRPC](https://github.com/uw-labs/bloomrpc) para simular uma solicitação local em sua API gRPC
```

2021-05-18 12:22 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/backend/beagle-grpc.md
> +#### 👉 Este tutorial está disponível no github com exemplos mais avançados, como headers e interceptors por exemplo. Se você estiver interessado, acesse-os [exemplos de back-end aqui](https://github.
```suggestion
#### 👉 Este tutorial está disponível no GitHub com exemplos mais avançados, como headers e interceptors por exemplo. Se você estiver interessado, [acesse-os aqui](https://github.com/ZupIT/beagle-helpers/backend/examples)
```

2021-05-21 18:35 UTC, carlossteinzup approved these changes

2021-05-24 15:10 UTC, uziasferreirazup requested changes

2021-05-24 15:10 UTC, uziasferreirazup commented on content/en/get-started/using-beagle-helpers/android/beagle-grpc.md
> +    implementation "br.com.zup.beagle:android:1.5.1"
this line is not necessary because the grpc lib already implements the beagle internally,

2021-05-24 15:10 UTC, uziasferreirazup commented on content/en/get-started/using-beagle-helpers/android/beagle-grpc.md
> +    kapt "br.com.zup.beagle:android-processor:1.5.1"
I think the example is better born updated using the latest version 1.7.1, @luismaximozup
is it possible to reference the dac version here via variable, because then I wouldn’t need to keep updating the example?

2021-05-24 15:10 UTC, uziasferreirazup commented on content/en/get-started/using-beagle-helpers/android/beagle-grpc.md
> +    implementation "br.com.zup.beagle:beagle-grpc:1.0.0"
normally the helper libs are following the beagle so it would be born with version 1.7.0

2021-05-24 15:14 UTC, uziasferreirazup commented on content/en/get-started/using-beagle-helpers/overview.md
> +description: 'Here you will find a library to help when you want to start a project using beagle for Android. These libs will facilitate the initial Beagle configuration in a project, avoiding some s
is that correct? before it had a file for each platform now it only has one global and just quoting android.

2021-05-24 17:16 UTC, luismaximozup commented on content/en/get-started/using-beagle-helpers/overview.md
> +description: 'Here you will find a library to help when you want to start a project using beagle for Android. These libs will facilitate the initial Beagle configuration in a project, avoiding some s
Yes, before it was the same file replicated on each platform, changing only the name of the platform. That way it gets more organized in my opinion.

2021-05-24 17:28 UTC, luismaximozup commented on content/en/get-started/using-beagle-helpers/android/beagle-grpc.md
> +    kapt "br.com.zup.beagle:android-processor:1.5.1"
```suggestion
    kapt "br.com.zup.beagle:android-processor:1.7.0"
```

2021-05-25 13:58 UTC, uziasferreirazup commented on content/en/get-started/using-beagle-helpers/overview.md
> +description: 'Here you will find a library to help when you want to start a project using beagle for Android. These libs will facilitate the initial Beagle configuration in a project, avoiding some s
ok, but in this file you only refer to android, wouldn't it be better to change the text and reference all platforms?

2021-06-01 12:28 UTC, igorgiumellizup requested changes

2021-06-01 12:28 UTC, igorgiumellizup commented on content/en/faq.md
> +The developer declares the backend screens and the expose the endpoints that represent them. These endpoints are called using Beagle to render the screen components on the web or mobile.
```suggestion
The developer declares the backend screens and the exposed endpoints that represent them. These endpoints are called using Beagle, to render the screen components on the web or mobile.
```

2021-06-01 12:28 UTC, igorgiumellizup commented on content/en/faq.md
> +Beagle works as a 'bridge' between front and backend, it is possible that the design components of your application have a parameter in backend which makes a native application possible.
```suggestion
Beagle works as a 'bridge' between front and backend, and it is possible for the design components of your application to have a parameter in the backend, making a native application possible.
```

2021-06-01 12:28 UTC, igorgiumellizup commented on content/en/faq.md
> +Beagle's solution is different from other tecnologies. It is a tool to make the development easier, it has UI oriented concept of continuous delivery. Beagle allows you to handle through backend, nat
```suggestion
Beagle's solution is different from other technologies. Beagle is a tool that makes mobile and web app development easier, and it has a UI oriented concept of continuous delivery. Through a backend project, Beagle also allows you to implement native components and change its layout.
```

2021-06-01 12:28 UTC, igorgiumellizup commented on content/en/faq.md
> +Yes! Unit tests like instrumented test work the same way on Beagle.
```suggestion
Yes! Unit tests, like instrumented tests, work the same way on Beagle.
```

2021-06-01 12:28 UTC, igorgiumellizup commented on content/en/faq.md
> +Yes! If your application already have the developed components in a design system, you are able to use them on Beagle. You only have to see if these components are defined and then it will be easy to
```suggestion
Yes! If your application already has the developed components in a design system, you are able to use them on Beagle. You only have to see if these components are defined and then it will be easy to register them on Beagle.
```

2021-06-01 12:28 UTC, igorgiumellizup commented on content/en/faq.md
> +Depends. All server driven application when requests the server a flow, it needs to be connected in order to receive a response from backend. The server driven flows cannot be solved without a connec
```suggestion
It depends. All server driven applications, when requesting the server in a flow, will need to be connected in order to receive a response from backend. The server driven flows cannot be solved without a connection. But, if your application is not 100% server driven, then there is a part of it that doesn't need to get online information, and then it will work. The application also can be configured to call other screens in case they are offline.
```

2021-06-01 12:28 UTC, igorgiumellizup commented on content/en/faq.md
> +### If my my internet connection is interrupted in the middle of the application flow?
```suggestion
### What If my internet connection is interrupted in the middle of the application flow?
```

2021-06-01 12:28 UTC, igorgiumellizup commented on content/en/faq.md
> +It's possible to create a BFF in a different language. However, we don't have ready `libs` to help you on this process, so it would be necessary that the developer create a mechanism to respect Beagl
```suggestion
It's possible to create a BFF in a different language. However, we don't have ready `libs` to help you on this process, so it would be necessary that the developer create a mechanism that respects Beagle's contracts.
```

2021-06-01 12:33 UTC, uziasferreirazup approved these changes

2021-06-01 13:03 UTC, igorgiumellizup requested changes

2021-06-01 13:03 UTC, igorgiumellizup commented on content/pt/get-started/using-beagle-helpers/Android/beagle-grpc.md
> +#### Etapa 2: adicione o plugin kotlin kapt e 3 dependências no gerenciador de dependências do seu aplicativo (gradle.gradle) <br>
```suggestion
#### Etapa 2: adicione o plugin Kotlin Kapt e 3 dependências no gerenciador de dependências do seu aplicativo (gradle.gradle) <br>
```

2021-06-04 18:15 UTC, igorgiumellizup approved these changes

2021-06-04 18:44 UTC, hernandazevedozup approved these changes

2021-06-04 19:21 UTC, merged