Feature/grid view
ZupIT/beagle-docs pull request #593
Opened 2021-05-31 20:34 UTC by jamessonpenhazup

Added Listview/Grid View Documentation with Multiple Templates.

2021-06-01 12:18 UTC, uziasferreirazup requested changes

2021-06-01 12:18 UTC, uziasferreirazup commented on content/en/api/components/layout/gridview.md
> +              ).applyStyle(
replace deprecated function to the new function setStyle

2021-06-01 12:18 UTC, uziasferreirazup commented on content/en/api/components/layout/gridview.md
> +              ).applyStyle(
this comment is valid to all `applystyle`

2021-06-01 12:20 UTC, uziasferreirazup requested changes

2021-06-01 12:20 UTC, uziasferreirazup commented on content/en/api/components/layout/gridview.md
> +O componente GridViewcomponent is responsible for defining a list in grid of items **recyclable** natively. These items can be any server-driven components. The use of GridView is more suitable for v
```suggestion
The GridView is responsible for defining a list in a grid of items **recyclable** natively. These items can be any server-driven components. The use of GridView is more suitable for visual content, recommended for situations where there is the repetition of components, but with different data.
```

2021-06-01 12:23 UTC, uziasferreirazup requested changes

2021-06-01 12:23 UTC, uziasferreirazup commented on content/en/api/components/layout/gridview.md
> +{{% /alert %}}
gridview has no template, remove this part.

2021-06-01 12:23 UTC, uziasferreirazup commented on content/en/api/components/layout/gridview.md
> +| templates           | List&lt;[ServerDrivenComponent]({{< ref path="/api/components" lang="en" >}}) &gt;  |            | It represents a template array, where each template corresponds to a cell in
gridview has no templates

2021-06-01 14:29 UTC, carlossteinzup commented on content/en/api/components/layout/gridview.md
> +description: "You will find here the description of the GridView component, its attributes and constructors"
```suggestion
description: "You will find here the GridView component description, it's attributes and constructors"
```

2021-06-01 14:34 UTC, carlossteinzup commented on content/en/api/components/layout/gridview.md
> +The componente GridView component is responsible for defining a grid of items **recyclable** natively. These items can be any server-driven components. The use of GridView is more suitable for visual
```suggestion
The GridView component defines how a group of itens will position itself in a **recyclable** grid layout natively. The items in a gridview could be any server-driven component. The GridView use is more suitable for visual content and is recommended for situations where an item repeats itself but with diferent data, like for example, a card with movies details.
```

2021-06-01 14:45 UTC, carlossteinzup commented on content/en/api/components/layout/gridview.md
> +See how the structure is represented:
```suggestion
This is how this component is structured:
```

2021-06-01 16:53 UTC, uziasferreirazup requested changes

2021-06-01 16:53 UTC, uziasferreirazup commented on content/en/api/components/layout/gridview.md
> +<!-- json-playground:listView.json
```suggestion
<!-- json-playground:gridView.json
```

2021-06-01 16:53 UTC, uziasferreirazup commented on content/en/api/components/layout/gridview.md
> +      "children": [
this attribute does not exist, the correct one would be datasource

2021-06-01 16:53 UTC, uziasferreirazup commented on content/en/api/components/layout/gridview.md
> +            children = listOf(
this attribute does not exist, the correct one would be `datasource`

2021-06-01 16:53 UTC, uziasferreirazup commented on content/en/api/components/layout/gridview.md
> +              },
```suggestion
              ).setStyle {
            size = Size.box(242, 225)
        }
```
change this in all code.

2021-06-01 16:53 UTC, uziasferreirazup commented on content/en/api/components/layout/listview.md
> +        Case("@{eq(item.race, 'Kandra')}"),
the object case doesn't exist to adjust this by `expressionof` I recommend creating this code by the backend and then pasting here

2021-06-01 16:53 UTC, uziasferreirazup commented
I didn't post the repeated comments, but I recommend looking at the entire post again.

2021-06-02 12:19 UTC, igorgiumellizup requested changes

2021-06-02 12:19 UTC, igorgiumellizup commented on content/en/api/components/layout/gridview.md
> +description: "You will find here the GridView component description, it's attributes and constructors"
Here you will the documentation about the GridView component, its attributes and constructors.

2021-06-02 12:19 UTC, igorgiumellizup commented on content/en/api/components/layout/gridview.md
> +The GridView component defines how a group of itens will position itself in a **recyclable** grid layout natively. The items in a gridview could be any server-driven component. The GridView use is mo
```suggestion
The GridView component defines how a group of items will place itself natively in a **recyclable** grid layout. The items in a GridView could be any server-driven component. The GridView use is more suitable for visual content and is recommended for situations where an item repeats itself but with different data, like a card with movies details for example.
```

2021-06-02 12:19 UTC, igorgiumellizup commented on content/en/api/components/layout/gridview.md
> +| templates           | List&lt;[ServerDrivenComponent]({{< ref path="/api/components" lang="en" >}}) &gt;  |            | It represents a template array, where each template corresponds to a cell in
```suggestion
| templates           | List&lt;[ServerDrivenComponent]({{< ref path="/api/components" lang="en" >}}) &gt;  |            | Represents a template array, where each template corresponds to a cell in the list through a `ServerDrivenComponent`.                                                          |
```

2021-06-02 12:19 UTC, igorgiumellizup commented on content/en/api/components/layout/gridview.md
> +  The template to use will be decided according to the property `case` of the template.
```suggestion
The template to use will be decided according to the property `case` of the template.  
```

2021-06-02 12:19 UTC, igorgiumellizup commented on content/en/api/components/layout/gridview.md
> + If all are `false`, then, the first template where `case` is omitted (default template) is used.
```suggestion
 If all are `false`, then the first template where `case` is omitted (default template) is used.
```

2021-06-02 12:19 UTC, igorgiumellizup commented on content/en/api/components/layout/listview.md
> +| templates           | List&lt;[ServerDrivenComponent]({{< ref path="/api/components" lang="en" >}}) &gt;  |            | It represents a template array, where each template corresponds to a cell in
```suggestion
| templates           | List&lt;[ServerDrivenComponent]({{< ref path="/api/components" lang="en" >}}) &gt;  |            | Represents a template array, where each template corresponds to a cell in the list through a `ServerDrivenComponent`.                                                          |
```

2021-06-02 12:19 UTC, igorgiumellizup commented on content/en/api/components/layout/listview.md
> +  The template to use will be decided according to the property `case` of the template.
```suggestion
The template to use will be decided according to the property `case` of the template.  
```

2021-06-02 12:19 UTC, igorgiumellizup commented on content/en/api/components/layout/listview.md
> + If all are `false`, then, the first template where `case` is omitted (default template) is used.
```suggestion
 If all are `false`, then the first template where `case` is omitted (default template) is used.
```

2021-06-02 12:19 UTC, igorgiumellizup commented on content/pt/api/components/layout/gridview.md
> +O componente GridView é responsável por definir uma lista em grade de itens **recicláveis** nativamente. Esses itens podem ser quaisquer componentes server driven. O uso do GridView é mais adequado p
O nativamente se refere a definição da lista, ou ao fato dos itens serem reciclados? Ou seja, seria a opção 1 ou 2?
Opção 1:  "O componente GridView é responsável por definir uma lista em grade de itens **recicláveis** nativamente"
Opção 2: "O componente GridView é responsável por definir nativamente uma lista em grade de itens **recicláveis**"

2021-06-02 12:19 UTC, igorgiumellizup commented on content/pt/api/components/layout/gridview.md
> +| templates    |List&lt;[ServerDrivenComponent]({{< ref path="/api/components" lang="pt" >}})&gt; |           | Representa um array de template, onde cada template corresponde a uma celula na lista a
```suggestion
| templates    |List&lt;[ServerDrivenComponent]({{< ref path="/api/components" lang="pt" >}})&gt; |           | Representa um array de template, onde cada template corresponde a uma célula na lista através de um `ServerDrivenComponent`.                                                              |
```

2021-06-02 12:19 UTC, igorgiumellizup commented on content/pt/api/components/layout/gridview.md
> +  O template a ser usado será decidido de acordo com a propriedade `case` do template.
```suggestion
O template a ser usado será decidido de acordo com a propriedade `case` do template.  
```

2021-06-03 13:22 UTC, uziasferreirazup approved these changes

2021-06-03 13:26 UTC, uziasferreirazup commented on content/pt/api/components/layout/gridview.md
> +O componente GridView é responsável por definir uma lista em grade de itens **recicláveis** nativamente. Esses itens podem ser quaisquer componentes server driven. O uso do GridView é mais adequado p
Oque muda na sua visão da opção 1 para opção 2? os dois texto resulta no mesmo sentido de reciclagem de view.

2021-06-03 13:26 UTC, paulomeurerzup approved these changes

2021-06-03 17:08 UTC, Tiagoperes approved these changes

2021-06-03 18:50 UTC, merged