Update release-notes.html
ZupIT/beagle-docs pull request #603
Opened 2021-06-03 14:46 UTC by tayronemachadozup

beagle 1.8 release notes

2021-06-03 15:51 UTC, matheusribeirozup commented on content/pt/release-notes.html
> +            <label class="titleList">New functionalities</label>
Esse release notes está no diretório `pt`, não deveria ser todo escrito em português?

2021-06-03 18:43 UTC, carlossteinzup commented on content/pt/release-notes.html
> +            <label class="titleList">New functionalities</label>
```suggestion
            <label class="titleList">Novas funcionalidades</label>
```

2021-06-03 19:09 UTC, carlossteinzup commented on content/pt/release-notes.html
> +                <img src="../assets/check.svg" class="iconSvg"/><a target="_blank" class="content__list__link" href="https://docs.usebeagle.io/v1.8/api/components/layout/gridview/">GridView component
```suggestion
                <img src="../assets/check.svg" class="iconSvg"/><a target="_blank" class="content__list__link" href="https://docs.usebeagle.io/v1.8/api/components/layout/gridview/">Componente: GridView</a>
```

2021-06-03 19:09 UTC, carlossteinzup commented on content/pt/release-notes.html
> +                <img src="../assets/check.svg" class="iconSvg"/><a target="_blank" class="content__list__link" href="https://docs.usebeagle.io/v1.7/api/components/layout/listview/">ListView with mult
```suggestion
                <img src="../assets/check.svg" class="iconSvg"/><a target="_blank" class="content__list__link" href="https://docs.usebeagle.io/v1.7/api/components/layout/listview/">Componente: ListView com multiplos templates</a>
```

2021-06-03 19:28 UTC, carlossteinzup commented on content/pt/release-notes.html
> +                <img src="../assets/check.svg" class="iconSvg"/><a target="_blank" class="content__list__link" href="https://docs.usebeagle.io/v1.8/api/actions/addchildren/">Add support to bind in fi
```suggestion
                <img src="../assets/check.svg" class="iconSvg"/><a target="_blank" class="content__list__link" href="https://docs.usebeagle.io/v1.8/api/actions/addchildren/">Adiciona suporte bind para o campo "value" na ação "add children"</a>
```

2021-06-03 19:29 UTC, carlossteinzup commented on content/pt/release-notes.html
> +            <label class="titleList">Impacts in iOS/Android/Web <img class='plataform__icon' src='https://docs.usebeagle.io/shared/IOS.svg'/> <img class='plataform__icon' src='https://docs.usebeagle.
```suggestion
            <label class="titleList">Impactos no iOS/Android/Web <img class='plataform__icon' src='https://docs.usebeagle.io/shared/IOS.svg'/> <img class='plataform__icon' src='https://docs.usebeagle.io/shared/Android.svg'/> <img class='plataform__icon' src='https://docs.usebeagle.io/shared/Web.svg'/></label>
```

2021-06-03 19:30 UTC, carlossteinzup commented on content/pt/release-notes.html
> +                <img src="../assets/check.svg" class="iconSvg"/><a target="_blank" class="content__list__link" href="https://github.com/ZupIT/beagle/releases/tag/1.8.0">Bugs fixed</a>
```suggestion
                <img src="../assets/check.svg" class="iconSvg"/><a target="_blank" class="content__list__link" href="https://github.com/ZupIT/beagle/releases/tag/1.8.0">Bugs corrigidos</a>
```

2021-06-03 19:36 UTC, carlossteinzup commented on content/pt/release-notes.html
> +            <p>Team Beagle</p>
```suggestion
            <p>Obrigado!</p>
            <p>Time Beagle</p>
```

2021-06-04 12:26 UTC, dantes-git requested changes
The correct thing is to update the release notes of the _content/en_ folder in English and the _content/pt_ folder in Portuguese. I also believe that there is a procedure to generate these release notes easier, talk to @luismaximozup to check if this really exists.

2021-06-04 13:37 UTC, closed without merging