fix: beagle helpers page
ZupIT/beagle-docs pull request #611
Opened 2021-06-04 19:23 UTC by luismaximozup

2021-06-14 14:48 UTC, jessica-tw reviewed
TW review done ;)

2021-06-14 14:48 UTC, jessica-tw commented on content/en/resources/gRPC/beagle-grpc-web.md
> +  In this section you will find all the info related to the client and the CLI of gRPC for Beagle Web (Angular and React).
```suggestion
  In this section, you will find information about the client and the CLI of gRPC for Beagle Web (Angular and React).
```

2021-06-14 14:48 UTC, jessica-tw commented on content/en/resources/gRPC/beagle-grpc-web.md
> +Proto files, in their content, are very similar to any interface we are used to on the daily basis, but with the .proto extension, where we define which objects and methods are likely to be used in t
```suggestion
- **Protobufs or Protocol Buffers**: They are structured data serialization mechanisms created by Google, which aim to keep contracts always valid and consistent, regarding the implementations that consume a gRPC service.

- **Proto files**: They are very similar to any interface we are used to on the daily basis, in their content. However, they have the .proto extension, where you can define which objects and methods are likely to be used in the service's communication.
```

2021-06-14 14:48 UTC, jessica-tw commented on content/en/resources/gRPC/beagle-grpc-web.md
> +gRPC is a technology that makes use of the **HTTP 2** protocol, however, this technology is not compatible with the current Web structure, so the structure created uses a Client and a CLI, where the
```suggestion
gRPC is a technology that uses the **HTTP 2** protocol, however, this technology is not compatible with the current Web structure. So, the new structure created uses a Client and a CLI: 
- The CLI is responsible for handling gRPC connections through a Proxy written with Go
- The Client is responsible for handling all requests made by Beagle to the Proxy.
```

2021-06-14 14:48 UTC, jessica-tw commented on content/en/resources/gRPC/beagle-grpc-web.md
> +To install the library, install it globally, for a better experience with the CLI, and then install it in your project using the following commands:
```suggestion
Install the library globally. For a better experience with the CLI, install it in your project using the following commands:
```

2021-06-14 14:48 UTC, jessica-tw commented on content/en/resources/gRPC/beagle-grpc-web.md
> +2. Then import the gRPC Client:
```suggestion
To start using, follow the next steps: 
**Step 1.** After installing the library in the project and globally, create the configuration file in the project's root folder, using: **`beagle-web-grpc init`** and then configure the attributes according to your needs.
**Step 2.**  Import the gRPC Client, check out below: 
```

2021-06-14 14:48 UTC, jessica-tw commented on content/en/resources/gRPC/beagle-grpc-web.md
> +4. Use the Beagle Web as usually.
```suggestion
**Step 3.** Start your proxy running the following command on the root of the project: **`beagle-web-grpc start-proxy`** or **`beagle-web-grpc spx`** or **`beagle-web-grpc start-proxy --mode your-mode`.**
**Step 4.** Use the Beagle Web as usually.
```

2021-06-14 14:48 UTC, jessica-tw commented on content/en/resources/gRPC/beagle-grpc-web.md
> +As gRPC is not compatible with the current structure of the Web, to support the technology, it is necessary to use a Proxy to establish the communication between the REST application and the gRPC Bac
```suggestion
gRPC is not compatible with the current structure of the Web, to support the technology, you have to use a Proxy to establish the communication between the REST application and the gRPC Backend application. 
Beagle team created a CLI (command-line interface), **beagle-web-grpc**, to make it easier to use the proxy and to provide all the necessary settings.
```

2021-06-14 14:48 UTC, jessica-tw commented on content/en/resources/gRPC/beagle-grpc-web.md
> +The gRPC Client for Beagle Web is what redirects grpc requests to the proxy, the client is used through `BeagleService` in React and the `Beagle` module in Angular, using the `fetchData` property, wh
```suggestion
The gRPC Client for Beagle Web is what redirects gRPC requests to the proxy. The client is used through `BeagleService` in React and `Beagle`'s module in Angular. When using the `fetchData` property, Beagle allows you to create custom HTTP requests, so it goes like this:
```

2021-06-14 14:48 UTC, jessica-tw commented on content/pt/resources/grpc/_index.md
> +  Esta seção contem algumas bibliotecas que irão te auxiliar a usar o Beagle com gRPC.
```suggestion
  Esta seção contém algumas bibliotecas ajudam você a usar o Beagle com gRPC.
```

2021-06-14 14:48 UTC, jessica-tw commented on content/pt/resources/grpc/beagle-grpc-web.md
> +Arquivos proto, em seu conteúdo, são bem parecidos com qualquer interface que estamos acostumados no dia-a-dia, porém com a extensão .proto, onde nele definimos quais são os objetos e métodos que são
```suggestion
É um framework open source que realiza chamadas RPC (Remote call procedure) por meio do protocolo HTTP2 em formato de two-way streaming, utilizando Protobufs como interfaces entre cliente e servidor.

- Protobufs ou Protocol Buffers: São mecanismos de serialização de dados estruturados criados pelo Google, que visam manter os contratos sempre válidos e coerentes quanto às implementações que consomem aquele serviço gRPC.

- Arquivos proto:  São bem parecidos com qualquer interface que você está acostumado no dia-a-dia, em seu conteúdo. Porém com a extensão .proto, onde nele você define quais são os objetos e métodos que podem ser usados na comunicação do serviço.
```

2021-06-14 14:48 UTC, jessica-tw commented on content/pt/resources/grpc/beagle-grpc-web.md
> +O gRPC é uma tecnologia que faz uso do protocolo **HTTP 2**, todavia, esta tecnologia não é compatível com a atual estrutura da Web, por isso a estrutura criada faz uso de um Cliente e um CLI, onde o
```suggestion
O gRPC é uma tecnologia que utiliza o protocolo **HTTP 2**, no entanto essa tecnologia não é compatível com a atual estrutura da Web. Por isso, a estrutura criada faz uso de um Cliente e um CLI:
- O CLI fica responsável por manipular as conexões gRPC através de um Proxy em Go; 
- O Cliente fica responsável por manipular todas requisições feitas pelo Beagle para o Proxy.
```

2021-06-14 14:48 UTC, jessica-tw commented on content/pt/resources/grpc/beagle-grpc-web.md
> +Para instalar a biblioteca, instale ela globalmente, para melhor experiência com o CLI e após instale a mesma em seu projeto com os seguintes comandos:
```suggestion
Instale a biblioteca globalmente. Para melhorar a experiência com o CLI, instale a mesma em seu projeto com os seguintes comandos:
```

2021-06-14 14:48 UTC, jessica-tw commented on content/pt/resources/grpc/beagle-grpc-web.md
> +2. Importe o cliente gRPC:
```suggestion
Para começar a utilizar, siga os passos abaixo:

**Passo 1.** Após a instalação das bibliotecas, crie o arquivo de configurações na pasta raiz do projeto, utilizando **`beagle-web-grpc init`** e configure os atributos com o que você precisa.
**Passo 2.** Importe o cliente gRPC, veja abaixo:
```

2021-06-14 14:48 UTC, jessica-tw commented on content/pt/resources/grpc/beagle-grpc-web.md
> +4. Utilize o Beagle normalmente.
```suggestion
**Passo 3.** Inicie o Proxy gRPC utilizando: **`beagle-web-grpc start-proxy`** ou **`beagle-web-grpc start-proxy --mode seu-modo-personalizado`**.
**Passo 4.** Utilize o Beagle normalmente.
```

2021-06-14 14:48 UTC, jessica-tw commented on content/pt/resources/grpc/beagle-grpc-web.md
> +Como o gRPC não é compatível com a estrutura atual da Web, para que a tecnologia tenha suporte, se faz necessário o uso de um Proxy para fazer a comunicação entre REST e o Backend gRPC, por isso cria
```suggestion
O gRPC não é compatível com a estrutura atual da Web, para que a tecnologia tenha suporte, você precisa usar um Proxy para fazer a comunicação entre REST e o Backend gRPC. 
Por isso o time do Beagle criou um CLI (Command-line Interface), **beagle-web-grpc**, para facilitar o uso do proxy e  adicionar todas as configurações necessárias.
```

2021-06-14 14:48 UTC, jessica-tw commented on content/pt/resources/grpc/beagle-grpc-web.md
> +O Cliente gRPC para Beagle Web é o que faz o redirecionamento das requisições grpc para o proxy, o cliente é utilizado através do `BeagleService` no React e do módulo `Beagle` no Angular, se valendo
```suggestion
O Cliente gRPC para Beagle Web faz o redirecionamento das requisições gRPC para o proxy. O cliente é utilizado por meio do `BeagleService` no React e do módulo `Beagle` no Angular. 
Se valendo da propriedade de `fetchData` em que o Beagle permite criar requisições HTTP customizadas, veja abaixo como a utilização será:
```

2021-06-17 13:42 UTC, arthurbleilzup submitted a review, later dismissed

2021-06-17 13:44 UTC, arthurbleilzup approved these changes

2021-06-18 14:00 UTC, paulomeurerzup requested changes

2021-06-18 17:24 UTC, paulomeurerzup approved these changes

2021-06-18 19:45 UTC, merged