Fix: custom widgets ios
ZupIT/beagle-docs pull request #617
Opened 2021-06-07 13:36 UTC by luisgustavozup

Fix custom widgets ios.

2021-06-07 19:09 UTC, uziasferreirazup requested changes

2021-06-07 19:09 UTC, uziasferreirazup commented on content/pt/resources/components/components-with-context.md
> +Se você quiser criar componentes customizados no iOS, é **necessário registrá-lo**! Veja como registrar [**aqui**]({{< ref path="/resources/customization/beagle-for-ios/custom-widget/simple-custom-wi
eu recomendo alterar o nome ao invez de ser custom widget set custom view, o nome "widget" facil muito mais sentido para flutter para android e ios recomendo fortemente usar view.

2021-06-14 13:40 UTC, jessica-tw reviewed
TW review done.

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Para exibir o componente recebido utizamos a `BeagleView`, logo a mesma retorna uma `UIView`. Para usar no meio do autoLayout é preciso desabilitar o `translatesAutoresizingMaskIntoConstraints` da vi
```suggestion
### Passo 2: Criar o Widget

Agora é o componente `ContainerTitle`, para trasformá-lo em um componente Beagle, adote o protocolo `Widget`, que é compatível com o `Decodable` e é responsável por decodificar as propriedades que seu widget expõem no backend.

1. Crie uma estrutura **ContainerTitleWidget** adotando protocolo `Widget`. A interface widget irá adicionar a property de **widgetProperties** e o método **toView**.

 * **widgetProperties:** A propriedade de aplicar estilo, id e acessibilidade.

 * **toView:** Método para retornar a view do componente criado.

2. A estrutura do `ContainerTitleWidget` com os parâmetros `title`, `child` e `widgetProperties` e o componente `ContainerTitle` criado no método `toView`.

3. Para exibir o componente recebido, utilize a `BeagleView`, logo a mesma retorna uma `UIView`. Para usar no meio do autoLayout é preciso desabilitar o `translatesAutoresizingMaskIntoConstraints` da view.
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +O widgetProperties tem sua propria parte decodificação, entao é preciso apenas passar o decoder para o objeto `WidgetProperties`.
```suggestion

Crie a parte de inicialização e decodificação do componente e você pode fazer isso de duas formas: 
1. Usando o `sourcery` gerador de código para a linguagem Swift.

2. Você pode fazer manualmente. 

**Sourcery:**

Para saber mais sobre como usar o `Sourcery`, acesse a seção [**Sourcery do Beagle**]({{< ref path="/resources/customization/beagle-for-ios/sourcery" lang="pt" >}})

**Manual:**

Manualmente, crie o init e a decodificação dos parâmetros **`title`** e **`widgetProperties`** da struct `BoxWidget`.
O widgetProperties tem a sua própria parte decodificação, então é preciso apenas passar o decoder para o objeto `WidgetProperties`.
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Para integrar o componente ao beagle é preciso utilizar o `sizeThatFits` ou `AutoLayoutWrapper`.
```suggestion
Integre o componente ao Beagle utilizando o `sizeThatFits` ou `AutoLayoutWrapper`. 
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Classe completa do Widget.
```suggestion
Veja a classe completa do Widget:
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Após registrar o seu componente de customização, você pode usá-lo  via server-driven.
```suggestion
### Passo 3: Registrar o Widget

É obrigatório **registrar o Widget no Beagle.** Dentro do arquivo de configuração, utilize o **`dependencies`** para registrar. 

{{% alert color="info" %}}
Para saber mais sobre o dependencies, veja a seção [**Beagle Dependencies**]({{< ref path="/resources/customization/beagle-for-ios/beagles-dependencies" lang="pt" >}}).
{{% /alert %}}

O método `register` possui dois construtores:
1: Passa apenas o `component`;
2:  Recebe o `component` e  o `named`.

* 1. **component:** Passa a classe do componente.

* 2. **named:** Parâmetro para setar o nome do componente. Não é obrigatório passar, por exemplo, quando o nome do componente é registrado diferente daquele que você criou no backend, ele será usado na deserializações para encontrar seu componente.

**Maneiras de Registrar**
```swift
// 1
dependencies.decoder.register(component: ContainerTitleWidget.self)

// 2
dependencies.decoder.register(component: ContainerTitleWidget.self, named: "ContainerTitleWidgetComponent")
```

Após registrar o seu componente de customização, você pode usá-lo  via server-driven.
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +O Beagle já possui alguns widgets básicos que podem ser usados para alterar a sua aplicação UI através do backend. No entanto, você pode adicionar novos componentes para fazer as views da sua aplicaç
```suggestion
O Beagle já possui alguns widgets básicos que podem ser usados para alterar a sua aplicação UI por meio do backend. No entanto, você pode adicionar novos componentes para fazer com que as views da sua aplicação sejam "visíveis" ao Beagle e que possam também ser usadas no backend. 
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Temos que criar a parte de inicialização e decodificação do componente, tem duas maneiras possíveis usando o `sourcery` gerador de código para a linguagem Swift, ou fazendo manualmente.
```suggestion
Crie a parte de inicialização e decodificação do componente, tem duas maneiras possíveis usando o `sourcery`:
1. Com o gerador de código para a linguagem Swift;
2.  Manualmente.
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Para usar o `Sourcery` pode encontrar nesse [**link**]({{< ref path="/resources/customization/beagle-for-ios/sourcery" lang="pt" >}})
```suggestion
Para usar o `Sourcery`, veja mais informações na seção [**Sourcery**]({{< ref path="/resources/customization/beagle-for-ios/sourcery" lang="pt" >}})
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +O widgetProperties tem sua propria parte decodificação, entao é preciso apenas passar o decoder para o objeto `WidgetProperties`.
```suggestion
Para fazer manualmente: 
1. Crie o init e a decodificação dos parâmetros `title` e `widgetProperties` da struct `BoxWidget`.
2. O widgetProperties tem sua própria parte decodificação, passe o decoder para o objeto `WidgetProperties`.
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +
```suggestion
Integre o componente ao Beagle usando o `sizeThatFits` ou `AutoLayoutWrapper`. 

```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Classe completa do Widget.
```suggestion
Veja a classe completa do Widget:
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +
```suggestion
### Passo 3: Registrar o Widget

É obrigatório **registrar o Widget no Beagle.** Dentro do arquivo de configuração utilize o **`dependencies`** para registar. 

{{% alert color="info" %}}
Para saber mais sobre o dependencies. [**Beagle Dependencies**]({{< ref path="/resources/customization/beagle-for-ios/beagles-dependencies" lang="pt" >}}).
{{% /alert %}}

O método `register` possui dois construtores, o primeiro passando apenas o `component` e segundo recebendo o `component` e `named`.

* **component:** Passa a classe do componente.

* **named:** Parâmetro para setar o nome do componente. Não é obrigatório passar. Um caso é quando o nome do componente é registrado diferente com que você criou no backend. Ele será usado na deserializações para encontrar seu componente.

```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Você pode usar o seu componente declarativamente assim como passá-lo por uma instância até o `BeagleScreenViewController` ou chamá-lo via método `toView()` para apresentar o`UIView` que aparece dentr
```suggestion
### Passo 4: Exibir o Componente

Você pode usar o seu componente declarativamente, passá-lo por uma instância até o `BeagleScreenViewController` ou chamá-lo via método `toView()` para apresentar o`UIView` que aparece dentro do seu próprio view controller.
```

2021-06-14 13:40 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Se você usar componentes mais complexos que estejam no  `UIViews` ou outros componentes não mencionados, o processo seria parecido.
```suggestion
Se você usar componentes mais complexos no  `UIViews` ou outros componentes não mencionados, o processo é parecido.
```

2021-06-23 12:21 UTC, igorgiumellizup requested changes

2021-06-23 12:21 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +    // Component `UILabel` created.
```suggestion
    // Creates component 'UILabel'
```

2021-06-23 12:21 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +    // Method to add component to hierarchy and position to superview.
```suggestion
    // Adds the component to the hierarchy and the position to the Superview.
```

2021-06-23 12:21 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Agora temos o componente `ContainerTitle`, para trasformar para um componente Beagle temos adotar o protocolo `Widget`, que é um protocolo que conforma com `Decodable` e é responsável por decodificar
```suggestion
Para transformar o componente `ContainerTitle` para um componente Beagle, temos que adotar o protocolo `Widget`, que é um protocolo compatível com `Decodable`, e é responsável por decodificar as propriedades que seu widget expõe no backend.
```

2021-06-30 13:54 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/_index.md
> +O Beagle já fornece alguns **widgets básicos**, você pode utilizá-los para criar a interface dos componentes de sua aplicação server-driven.
```suggestion
O Beagle já fornece alguns **widgets básicos**, e você pode utilizá-los para criar a interface dos componentes de sua aplicação server-driven. 
```

2021-06-30 14:35 UTC, igorgiumellizup reviewed
B1, além das sugestões que mencionei, tem outros pontos de atenção:
- Cuidar com redundância, ex comentar em cima de um método coisas como "método para bla bla bla". Já se sabe que é um método. Neste caso, apenas informe o que ele faz
- Comentar no código apenas quando realmente é relevante e vai agregar no entendimento do mesmo. Ou seja, se voce tem um método chamado getUser, não precisa comentar coisas como "método que retorna usuário"
- Procurar manter o padrão de case. Em alguns lugares, temos Beagle, em outros, beagle. Idem para Widget / widget, server-driven / server driven, backend / back-end, etc. 
- Alguns comentários estão com ponto final e outros não. Escolher um padrão
- Cuidar com o uso excessivo da palavra "você"

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/_index.md
> +No entanto, a sua aplicação pode precisar de componentes mais especializados \(Custom Views\) e, para torná-los "visíveis" ao Beagle, você precisa criar um **widget específico**. Você pode criar inúm
```suggestion
No entanto, a sua aplicação pode precisar de componentes mais especializados \(Custom Views\) e, para torná-los "visíveis" ao Beagle, pode-se criar um **widget específico**. É possível criar inúmeros componentes novos, mas é preciso que eles **tornem as Views do aplicativo "visíveis" para o Beagle.**
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/_index.md
> +No entanto, a sua aplicação pode precisar de componentes mais especializados \(Custom Views\) e, para torná-los "visíveis" ao Beagle, você precisa criar um **widget específico**. Você pode criar inúm
Nesta sugestão, procurei refazer a mensagem diminuindo a palavra "você". Se você concordar, sugiro rever o restante do PR.

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Para saber mais sobre como criar um componente veja, [**Widget Customizado Simples**]({{< ref path="/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget" lang="pt" >}}).
```suggestion
Para saber mais sobre como criar um componente, veja [**Widget Customizado Simples**]({{< ref path="/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget" lang="pt" >}}).
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Agora é o componente `ContainerTitle`, para trasformá-lo em um componente Beagle, adote o protocolo `Widget`, que é compatível com o `Decodable` e é responsável por decodificar as propriedades que se
```suggestion
Agora falaremos do componente `ContainerTitle`. Para transformá-lo em um componente Beagle, adote o protocolo `Widget`, que é compatível com o `Decodable` e é responsável por decodificar as propriedades que seu widget expõe no backend.
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +3. Para exibir o componente recebido, utilize a `BeagleView`, logo a mesma retorna uma `UIView`. Para usar no meio do autoLayout é preciso desabilitar o `translatesAutoresizingMaskIntoConstraints` da
```suggestion
3. Para exibir o componente recebido, utilize a `BeagleView`, já que a mesma retorna uma `UIView`. Para usar no meio do autoLayout é preciso desabilitar o `translatesAutoresizingMaskIntoConstraints` da view.
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +3. Para exibir o componente recebido, utilize a `BeagleView`, logo a mesma retorna uma `UIView`. Para usar no meio do autoLayout é preciso desabilitar o `translatesAutoresizingMaskIntoConstraints` da
Verificar se esta sugestão muda a regra de negócio pretendida

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Crie a parte de inicialização e decodificação do componente e você pode fazer isso de duas formas:
```suggestion
Crie a parte de inicialização e decodificação do componente. É possível ser feito de duas formas: 
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +2. Você pode fazer manualmente.
```suggestion
2. Manualmente. 
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +O widgetProperties tem a sua própria parte decodificação, então é preciso apenas passar o decoder para o objeto `WidgetProperties`.
O que você acha de repensarmos a palavra "decoder"? Será que o leitor vai entender do que se trata?

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Fazendo as configurações com o `AutoLayoutWrapper`.
Espaço a+ antes do Desabilite...

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +**`sizeThatFits:`** Método para implementar sua lógica de tamanho, usado na classe do componente customizado.
```suggestion
**`sizeThatFits:`** Método para implementar a lógica de tamanho. Este método é usado na classe do componente customizado.
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +    // Component `UILabel` created.
```suggestion
    // Component `UILabel`
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +    // Initialization part of the class.
```suggestion
    // Class initialization
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +    // Implementation sizeThatFits
Penso que este comentário não agrega muito, já que o método está bem claro

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +    // Method to add component to hierarchy and pass position.
```suggestion
    // Adds component to hierarchy and configures position
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +É obrigatório **registrá-lo no Beagle.** Dentro do arquivo de configuração do beagle utilize o `dependencies` para registar.
```suggestion
É obrigatório **registrá-lo no Beagle.** Dentro do arquivo de configuração do Beagle, utilize o `dependencies` para registar. 
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +É obrigatório **registrá-lo no Beagle.** Dentro do arquivo de configuração do beagle utilize o `dependencies` para registar.
Está claro onde fica este arquivo?

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +* **component:** Passa a classe do componente.
```suggestion
* **component:** Classe do componente.
```

2021-06-30 14:35 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +* **named:** Parâmetro para setar o nome do componente. Não é obrigatório passar. Um caso é quando o nome do componente é registrado diferente com que você criou no backend. Ele será usado na deseria
```suggestion
* **named:** Nome do componente. Não é obrigatório informar-lo. Utiliza-se por exemplo quando o nome do componente é registrado diferentemente com que você criou no backend. Ele será usado na deserializações para encontrar seu componente.
```

2021-07-14 12:58 UTC, luisgustavozup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +    // Implementation sizeThatFits
Vou remover os comentários

2021-07-20 14:48 UTC, igorgiumellizup approved these changes

2021-07-20 16:55 UTC, jacoabreuzup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +1. Usando o `sourcery` gerador de código para a linguagem Swift.
```suggestion
1. Usando o  gerador de código para a linguagem Swift: `sourcery`.
```

2021-07-20 17:04 UTC, jacoabreuzup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +O widgetProperties tem a sua própria parte decodificação, então é preciso apenas passar o decoder para o objeto `WidgetProperties`.
Aqui você quis dizer "O widgetProperties tem a sua própria parte DE decodificação" ?

2021-07-20 17:07 UTC, igorgiumellizup approved these changes

2021-07-20 17:07 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +### Passo 1: Criar o componente Customizado
```suggestion
### Passo 1: Criar o componente customizado
```

2021-07-20 17:07 UTC, igorgiumellizup commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +-  Desabilite o `translatesAutoresizingMaskIntoConstraints` da view do componente;
```suggestion
- Desabilite o `translatesAutoresizingMaskIntoConstraints` da view do componente;
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Agora falaremos do componente `ContainerTitle`. Para transformá-lo em um componente Beagle, adote o protocolo `Widget`, que é compatível com o `Decodable` e é responsável por decodificar as proprieda
```suggestion
Para transformar o componente `ContainerTitle` em um componente Beagle, adote o protocolo `Widget`. Ele é compatível com o `Decodable` e responsável por decodificar as propriedades que seu widget expõe no backend.
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +3. Para exibir o componente recebido, utilize a `BeagleView`, já que a mesma retorna uma `UIView`. Para usar no meio do autoLayout é preciso desabilitar o `translatesAutoresizingMaskIntoConstraints`
```suggestion
Para criar um Widget: 
1. Crie uma estrutura **ContainerTitleWidget** e adote o protocolo `Widget`. A interface widget irá adicionar a property de **widgetProperties** e o método **toView**.

 * **widgetProperties:** Propriedade para aplicar estilo, id e acessibilidade;

 * **toView:** Método para retornar a view do componente criado.

2. Adicione a estrutura do `ContainerTitleWidget` com os parâmetros `title`, `child` e `widgetProperties`, e o componente `ContainerTitle`, já criado no método `toView`.

3. Utilize a `BeagleView` para exibir o componente recebido, ela retorna uma `UIView`. 
Se você quiser usar essa classe no meio do autoLayout é preciso desabilitar o `translatesAutoresizingMaskIntoConstraints` da view.
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +3. Para exibir o componente recebido, utilize a `BeagleView`, já que a mesma retorna uma `UIView`. Para usar no meio do autoLayout é preciso desabilitar o `translatesAutoresizingMaskIntoConstraints`
- Eu adicionei algumas palavras que entendi que faltavam no texto, olhe se faz sentido ou se precisa alterar, please. ;)

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +**`sizeThatFits:`** Método para implementar a lógica de tamanho. Este método é usado na classe do componente customizado.
```suggestion
**`sizeThatFits:`** É um método para implementar a lógica de tamanho. É usado na classe do componente customizado.
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +* **named:** Nome do componente. Não é obrigatório informar-lo. Utiliza-se por exemplo quando o nome do componente é registrado diferentemente com que você criou no backend. Ele será usado na deseria
```suggestion
### Passo 3: Registrar o Widget

É obrigatório **registrar o Widget no Beagle.** Para fazer isso, acesse o arquivo de configuração do Beagle e utilize o `dependencies` para registrar. 

{{% alert color="info" %}}
Para saber mais sobre o dependencies, veja a seção [**Beagle Dependencies**]({{< ref path="/resources/customization/beagle-for-ios/beagles-dependencies" lang="pt" >}}).
{{% /alert %}}

O método `register` possui dois construtores:
1. Passa apenas o `component`;
2. Recebe o `component` e `named`.

* **component:** A classe do componente.

* **named:** É o nome do componente e não é obrigatório informá-lo. Você pode usar quando você registrar um nome de componente diferente do que você criou no backend. 
Ele é usado na deserializações para encontrar o seu componente.
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Você pode usar o seu componente declarativamente, passá-lo por uma instância até o `BeagleScreenViewController` ou chamá-lo via método `toView()` para apresentar o`UIView` que aparece dentro do seu p
```suggestion
### Passo 4: Exibir o componente

Você pode usar o seu componente declarativamente e passá-lo por uma instância até o `BeagleScreenViewController`. A outra opção é chamá-lo via o método `toView()` para apresentar o`UIView` que aparece dentro do seu próprio view controller.
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/serverdrivencomponent-custom-widget.md
> +Veja abaixo um exemplo renderizado:
```suggestion
Veja abaixo um exemplo de um componente renderizado:
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +O Beagle já possui alguns widgets básicos que podem ser usados para alterar a sua aplicação UI por meio do backend. No entanto, você pode adicionar novos componentes para fazer com que as views da su
```suggestion
O Beagle já possui alguns widgets básicos que podem ser usados para alterar a sua aplicação UI por meio do backend. No entanto, você pode adicionar novos componentes para que as views da sua aplicação sejam "visíveis" ao Beagle e que elas possam também ser usadas no backend. 
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Agora tem a estrutura do `BoxWidget` com os parâmetros `title` e `widgetProperties` e o componente `Box` criado no método `toView`.
```suggestion
Para transformar o componente `Box` em um componente Beagle, adote o protocolo `Widget`. 
Esse protocolo é de acordo com o `Decodable` e decodifica as propriedades que seu widget expõem ao backend.

Siga os passos abaixo:
1. Crie uma struct BoxWidget com protocolo `Widget`;
2. A interface widget adiciona a property de **widgetProperties** e o método **toView**.

 * **widgetProperties:** A propriedade de aplicar estilo, id e acessibilidade;

 * **toView:** Método para retornar a view do componente criado.

A estrutura do `BoxWidget` possui os parâmetros `title` e `widgetProperties` e o componente `Box` precisa ser criado no método `toView`.
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Agora tem a estrutura do `BoxWidget` com os parâmetros `title` e `widgetProperties` e o componente `Box` criado no método `toView`.
'Esse protocolo é de acordo com o `Decodable`' > tem algum outro lugar que menciona esse protocolo? Seria legal linkar para o leitor ;)

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Fazendo as configurações com o `AutoLayoutWrapper`.
```suggestion
**`AutoLayoutWrapper:`** O objeto calcula o tamanho considerando as restrições do componente.

Siga os passos para configurar:
1. Desabilite o `translatesAutoresizingMaskIntoConstraints` da view do componente;
2. Adicione a view do componente dentro do `AutoLayoutWrapper`.
3. Faça as configurações com o `AutoLayoutWrapper`:

Veja abaixo como configurar com o `AutoLayoutWrapper`:
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Classe completa do Widget.
```suggestion
Classe completa do Widget:
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +A classe do componente customizado com `sizeThatFits` implementado.
```suggestion
Veja a classe do componente customizado com `sizeThatFits` implementado:
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +* **named:** Parâmetro para setar o nome do componente. Não é obrigatório passar. Um caso é quando o nome do componente é registrado diferente com que você criou no backend. Ele será usado na deseria
```suggestion
É obrigatório **registrar o Widget no Beagle.** Para fazer isso, acesse o arquivo de configuração do Beagle e utilize o `dependencies` para registrar. 

{{% alert color="info" %}}
Para saber mais sobre o dependencies, veja a seção [**Beagle Dependencies**]({{< ref path="/resources/customization/beagle-for-ios/beagles-dependencies" lang="pt" >}}).
{{% /alert %}}

O método `register` possui dois construtores:
1. Passando apenas o `component`;
2. Recebendo o `component` e `named`.

* **component:** Passa a classe do componente.

* **named:** Parâmetro para definir o nome do componente e não é obrigatório. Você pode usar quando você registrar um nome de componente diferente do que você criou no backend. 
Ele é usado na deserializações para encontrar o seu componente.
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Você pode usar o seu componente declarativamente, passá-lo por uma instância até o `BeagleScreenViewController` ou chamá-lo via método `toView()` para apresentar o`UIView` que aparece dentro do seu p
```suggestion
Você pode usar o seu componente declarativamente, passá-lo por uma instância até o `BeagleScreenViewController`. Outra opção é chamá-lo via método `toView()` para apresentar o`UIView` que aparece dentro do seu próprio view controller.
```

2021-07-29 12:58 UTC, jessica-tw commented on content/pt/resources/customization/beagle-for-ios/custom-widget/simple-custom-widget.md
> +Para saber mais como exibir o Componente. [**Como exibir uma tela**]({{< ref path="/get-started/using-beagle/ios" lang="pt" >}}).
```suggestion
Para saber mais como exibir o Componente, veja a seção [**Como exibir uma tela**]({{< ref path="/get-started/using-beagle/ios" lang="pt" >}}).
```

2021-08-02 12:47 UTC, carlossteinzup commented
it was changed to draft since the structure has changed and it is no longer possible to merge this without breaking the new structure. This branch needs to be updated first.

2021-08-10 17:49 UTC, closed without merging