refact: update installing-beagle
ZupIT/beagle-docs pull request #648
Opened 2021-06-16 10:46 UTC by viniciusguardieirozup

2021-06-16 18:23 UTC, carlossteinzup commented on content/en/android/installing-beagle.md
> +</table>
```suggestion
| **Attribute** | **Type** | **Definition** |
| :----------- | :------ | :------ |
| environment | Environment | Attribute responsible for informing Beagle about the current build status of the application. |
| baseUrl | String | Informs the base URL used in Beagle in the application. If you are using the emulator, [**check here to define this attribute**](https://developer.android.com/studio/run/emulator-networking.html#networkaddresses)  |
| isLoggingEnabled | Boolean | Attribute that enables or disables all logs that Beagle generates.|
| cache	| Cache	| Object responsible for managing the cache of Beagle requests. |
```

2021-06-16 18:26 UTC, carlossteinzup approved these changes

2021-06-18 14:32 UTC, matheusribeirozup commented on content/en/android/installing-beagle.md
> + * Proguard - you can obfuscate your code using proguard, it's necessary a configuration to not obfuscate some class that could be serialized and deserialized by Beagle
I think this text is not reflecting well the proguard in beagle, because by default all settings are already pre-applied, only if the user wants additional customizations.

2021-06-18 20:10 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> +**Passo 4️:** Feitas as configurações anteriores, o Android levará um tempo pra construir o projeto porque estará sincronizando todas as dependências inicias para inicializar o projeto
```suggestion
**Passo 4️:** Depois de terminar as configurações, o Android levará um tempo pra construir o projeto porque ele precisa sincronizar todas as dependências iniciais para inicializar o projeto.
```

2021-06-18 20:10 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> +Quando a inicialização for concluída, você verá esta página:
```suggestion
Quando a inicialização for concluída, você verá a página abaixo:
```

2021-06-18 20:10 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> +Para adicionar o Beagle em seu projeto Android e poder aproveitar desse framework, siga os passos abaixo:
```suggestion
Para adicionar o Beagle em seu projeto Android e utilizar esse framework, siga os passos abaixo:
```

2021-06-18 20:10 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> +Lembre de sempre usar a mesma versão do Beagle utilizada no seu BFF para evitar possíveis problemas
```suggestion
Use a mesma versão do Beagle utilizada no seu BFF para evitar possíveis problemas.
```

2021-06-18 20:10 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> +Feita a atualização, você precisa criar uma classe `BeagleConfig` e configurar seus atributos, como mostra o exemplo abaixo:
```suggestion
**Passo 1: Criar uma classe BeagleConfig**

Depois de finalizar a atualização, você precisa criar uma classe `BeagleConfig` e configurar seus atributos, veja o exemplo abaixo:
```

2021-06-18 20:10 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> +Faça a configuração das classes com bastante atenção, pois se você anotá-las com `BeagleComponent`, o Beagle espera que elas tenham construtores vazios.
```suggestion
Cuidado ao fazer a configuração das classes, porque se você anotá-las com `BeagleComponent`, o Beagle espera que elas tenham construtores vazios.
```

2021-06-18 20:10 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> +
```suggestion
**Passo 2: Criar o BeagleSetup**

```

2021-06-18 20:10 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> +**Passo 3:** Criar a classe Application
```suggestion
**Passo 3: Criar a classe Application**
```

2021-06-18 20:10 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> +**Passo 4:** Atualizar seu Android Manifest.xml
```suggestion
**Passo 4: Atualizar seu Android Manifest.xml**
```

2021-06-18 20:10 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> +Por fim, você deve atualizar novamente o seu `AndroidManifest.xml` e definir a `AppApplication` que foi criada como o arquivo de inicialização da aplicação, como no exemplo abaixo:
```suggestion
Atualize novamente o seu `AndroidManifest.xml` e defina a `AppApplication` que foi criada como o arquivo de inicialização da aplicação, veja o exemplo abaixo:
```

2021-06-21 16:56 UTC, carlossteinzup commented on content/en/android/_index.md
> +description: Here, you'll find more about Beagle for Android
```suggestion
description: This section holds information on how to add Beagle into an Android project
```

2021-06-21 16:57 UTC, carlossteinzup commented on content/en/android/installing-beagle.md
> +After you have installed the program, follow the steps below:
```suggestion
After you have installed Android Studio, follow the steps below:
```

2021-06-21 16:58 UTC, carlossteinzup commented on content/en/android/installing-beagle.md
> +**Step 4️: After you made the previous configurations, Android will take some time to build the project because it will be synchronizing all the dependencies to initialize the project.**
```suggestion
**Step 4️: After the previous configurations, Android will take some time to build the project since it will synchronize all dependencies to initialize this project.**
```

2021-06-21 17:04 UTC, carlossteinzup commented on content/en/android/installing-beagle.md
> +You have to adjust your repository's dependencies to receive Beagle. To do so, use the following configuration to **download Beagle's library.**
```suggestion
You must add `mavenCentral()` in the *allprojects repository's dependencies* to set the resource for Beagle. To do so, use the following configuration to **download Beagle's library.**
```

2021-06-21 17:20 UTC, carlossteinzup commented on content/en/android/installing-beagle.md
> +After you have completed the first configuration, now you need to include the `kapt` and Beagle's plugin as dependencies on your dependency manager, check out the example below:
```suggestion
Now you need to include the `kapt` and `Beagle's` plugin on your dependency manager, check out the example below:
```

2021-06-21 17:41 UTC, jessica-tw commented on content/en/android/installing-beagle.md
> + * Analytics - you can configure an analytics to generate screen and actions reports
```suggestion
 * **Action:** You can create custom actions to be executed by your widgets according to the user interaction.
 * **Navigation Animation:** You can customize Beagle screen navigation animations.
 * **Beagle Activity:** You can customize the activity that will be displayed when a server-driven screen was called.
 * **Network Client:** You can customize the network client to configure in a way Beagle will make requests.
 * **Cache:** You can customize the cache to save server-driven screens.
 * **Loading and errors treatment:** You can customize the error treatment and loading of server-driven screens.
 * **Proguard:** You can obfuscate your code using Proguard, all settings are already set internally. If you want to create custom components or change any Proguard's rules, Beagle supports it.
 * **Deep Link handler:** You can configure the Deep Link Handler to navigate from a server-driven screen to a native screen.
 * **Image Downloader:** You can customize how images will be downloaded to be displayed by Beagle.
 * **Design System:** You can customize your design system to build more beautiful screens and Beagle will display them.
 * **Serializer and Deserializer:** You can customize how Beagle will serialize and deserialize.
 * **Log:** You can customize how the logs generated by Beagle will be displayed.
 * **Widget:** You can create more specific components for your project and you can use them to build your server-driven screens.
 * **Operations:** You can create your operations to easily manipulate context by your backend.
 * **Analytics:** You can configure the analytics to generate screen and actions reports. 
```

2021-06-21 17:41 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> + * Analytics - você pode configurar um analytics para gerar reportes de telas e ações
```suggestion
 * **Ações:** Você pode criar ações customizadas para serem executadas pelos widgets conforme interações do usuário.
 * **Animações de navegação:** Você pode customizar as animações de navegação das telas do Beagle.
 * **Beagle Activity:** Você pode customizar a activity que será exibida quando uma tela server-driven for chamada.
 * **Camada de Rede:** Você pode customizar a camada de rede para configurar a forma que o Beagle irá fazer as requisições.
 * **Cache:** Você pode customizar o cache para salvar as telas server-driven.
 * **Carregamento e tratamento de erros:** Você pode customizar o tratamento de erro e o loading das telas server-driven.
 * **Proguard:** Você pode ofuscar e otimizar seu código usando Proguard, todas as configurações já estão definidas internamente. Caso queira criar componentes customizados ou alterar alguma regra para o Proguard, o Beagle oferece suporte para isso.
 * **Deep Link handler:** Você pode configurar o Deep Link Handler para ter navegação de uma tela server-driven para uma tela nativa.
 * **Image Downloader:** Você pode customizar a forma como as imagens serão baixadas para serem exibidas pelo Beagle.
 * **Design System:** Você pode customizar seu design system para construir telas mais bonitas.
 * **Serializador e Desserializador:** Você pode customizar a forma como o Beagle serializa e desserializa.
 * **Log:** Você pode customizar a maneira como os logs gerados pelo Beagle serão exibidos.
 * **Widget:** Você pode criar componentes específicos para seu projeto e utilizá-los na criação de telas server-driven.
 * **Operações:** Você pode criar suas operações para manipular o Context de uma forma mais simples através do seu backend.
 * **Analytics:** Você pode configurar um analytics para gerar reportes de telas e ações. 
```

2021-06-21 17:41 UTC, jessica-tw commented on content/pt/android/installing-beagle.md
> + * Analytics - você pode configurar um analytics para gerar reportes de telas e ações
Eu ainda acho interessante linkar esses tópicos para outras partes da documentação onde eles estão mais detalhados.

2021-06-21 18:20 UTC, viniciusguardieirozup commented on content/pt/android/installing-beagle.md
> + * Analytics - você pode configurar um analytics para gerar reportes de telas e ações
Sim, iremos fazer isso, como estamos mudando a estrutura da doc esses links ainda não existem, ai conforme for criando na nova estrutura iremos adicionando

2021-06-21 21:36 UTC, matheusribeirozup commented on content/en/android/installing-beagle.md
> +- Create a Android project from scratch
```suggestion
- Create an Android project from scratch
```

2021-06-21 21:37 UTC, matheusribeirozup commented on content/en/android/installing-beagle.md
> +- Add Beagle on your project (can be in a existing project)
```suggestion
- Add Beagle on your project (can be in an existing project)
```

2021-06-21 21:41 UTC, matheusribeirozup commented on content/en/android/installing-beagle.md
> +Remember to always check if you're using the latest version of Beagle. To see this information, you just have to pass your mouse above the version number. After that, sync your machine.
```suggestion
Remember to always check if you're using the latest version of Beagle. To see this information, you just have to pass your cursor above the version number. After that, sync your project.
```

2021-06-21 21:46 UTC, matheusribeirozup commented on content/en/android/installing-beagle.md
> +
As in the past we had to teach users to put this parameter in their project for local testing, I suggest adding it to the manifest along with a brief description.
```suggestion
        android:usesCleartextTraffic="true"
```

2021-06-21 21:46 UTC, matheusribeirozup commented on content/en/android/installing-beagle.md
> + * **Proguard:** You can obfuscate your code using Proguard, all settings are already set internally. If you want to create custom components or change any Proguard's rules, Beagle supports it.
```suggestion
 * **Proguard:** You can optimize and obfuscate your code using Proguard, all settings are already set internally. If you want to create custom components or change any Proguard's rules, Beagle supports it.
```

2021-06-21 21:48 UTC, matheusribeirozup commented on content/en/android/installing-beagle.md
> + * **Navigation Animation:** You can customize Beagle screen navigation animations.
```suggestion
 * **Navigation Animation:** You can customize the enter and exit animations on Beagle navigation.
```

2021-06-23 12:26 UTC, igorgiumellizup commented on content/en/android/_index.md
> +description: This section holds information on how to add Beagle into an Android project
I suggest using **contains** instead of **holds**
Holds in this context is not very common

2021-06-23 12:41 UTC, igorgiumellizup requested changes

2021-06-23 12:41 UTC, igorgiumellizup commented on content/en/android/installing-beagle.md
> +- Add Beagle on your project (can be in an existing project)
```suggestion
- Add Beagle in your project (can be in an existing project)
```

2021-06-23 12:41 UTC, igorgiumellizup commented on content/en/android/installing-beagle.md
> +* Inform your project's name. On this example, we'll call `BeagleApp`.
```suggestion
* Inform your project's name. On this example, we'll call it `BeagleApp`.
```

2021-06-23 12:41 UTC, igorgiumellizup commented on content/en/android/installing-beagle.md
> +**Step 1: Configure the dependencies**
I suggest adding that the information bellow needs to be placed inside the build.gradle file

2021-06-23 12:41 UTC, igorgiumellizup commented on content/en/android/installing-beagle.md
> +After you have created the class shown in the previous step and annotated with @BeagleComponent, just build your project (press CTRL + F9) and Beagle will automatically create a BeagleSetup class, se
I suggest showing how to build the project through menu, in Android Studio. Sometimes, hotkeys don't work, specially depending on the OS

2021-06-23 16:54 UTC, viniciusguardieirozup commented on content/en/android/_index.md
> +description: This section holds information on how to add Beagle into an Android project
Thanks for the suggestion, I'll do this!

2021-06-23 16:54 UTC, viniciusguardieirozup commented on content/en/android/installing-beagle.md
> +**Step 1: Configure the dependencies**
Thanks for the suggestion, I'll do this!

2021-06-23 16:54 UTC, viniciusguardieirozup commented on content/en/android/installing-beagle.md
> +After you have created the class shown in the previous step and annotated with @BeagleComponent, just build your project (press CTRL + F9) and Beagle will automatically create a BeagleSetup class, se
Thanks for the suggestion, I'll do this!

2021-06-24 17:28 UTC, carlossteinzup approved these changes

2021-06-24 21:26 UTC, igorgiumellizup approved these changes

2021-06-25 19:08 UTC, merged