refactor: trying to improve main overview page of the doc
ZupIT/beagle-docs pull request #651
Opened 2021-06-18 15:25 UTC by theffc

In progress

2021-06-23 13:08 UTC, igorgiumellizup commented on content/en/overview.md
> +The *Image* component, for example, has this attribute named `path` that can receive `remote` or `local` paths to the image data. Here we use a `remote` image by providing an `url` which Beagle will
```suggestion
The *Image* component, for example, has this attribute named `path` that can receive `remote` or `local` paths to the image data. Here we use a `remote` image by providing a `url` which Beagle will use to request the image when the component gets rendered.
```

2021-06-23 13:08 UTC, igorgiumellizup commented on content/en/overview.md
> +> You can have full control on the network request triggered by this remote image, you just need to configure your own Network Layer as a Beagle Dependency. Beagle have many configurable pieces like
```suggestion
> You can have full control on the network request triggered by this remote image, you just need to configure your own Network Layer as a Beagle dependency. Beagle have many configurable fragments like that and you can see more in [Customization]({{< ref path="resources/customization/_index.md" >}}).
```

2021-06-23 13:08 UTC, igorgiumellizup commented on content/en/overview.md
> +Finally, let's take a closer look into the `style` attribute, which describes how to position and layout components and their children. Most of components have this attribute, and it's responsible fo
```suggestion
Finally, let's take a closer look into the `style` attribute, which describes how to position and layout components and their children. Most of components have this attribute, and it's responsible for an important Beagle feature: **developers have control *through backend* on UI positioning**. You can see this feature by changing the `flexDirection` attribute to `ROW` inside [Beagle's Playground](https://playground.usebeagle.io/), and you will see the same views positioned horizontally. In a real application, you could deploy this exact change in your backend, and they would be *immediately* reflected in your frontend – even on mobile platforms, without needing mobile stores update.
```

2021-06-23 13:08 UTC, igorgiumellizup commented on content/en/overview.md
> +If you are familiar with web development, you probably already know how to use `flex` because it's used as a cross-platform [CSS Flexbox](https://www.w3schools.com/css/css3_flexbox.asp). To accomplis
```suggestion
If you are familiar with web development, you probably already know how to use `flex` because it's used cross-platform [CSS Flexbox](https://www.w3schools.com/css/css3_flexbox.asp). To accomplish this behind the scenes, we leverage a library called [**Yoga**](https://yogalayout.com), that is a cross-platform C++ library developed by Facebook and used in other projects (e.g: React Native). If you are not familiar with Flexbox, it takes some time to get used to it, but we bet you will really enjoy it due to its simplicity, power and flexibility. [Our documentation]({{< ref path="resources/components-positioning/_index.md" >}}), and [Yoga's own documentation](https://yogalayout.com/docs) can help you to quickly understand it.
```

2021-06-23 16:52 UTC, theffc commented
@igorgiumellizup thanks for the suggestions! 
I reviewed each one and applied or changed them a little bit in the commit [b88a78c](https://github.com/ZupIT/beagle-docs/pull/651/commits/b88a78cbc2f4fcf8633472ad3233bb0497228187).
I resolved all suggestions just to make this PR cleaner, but feel free to reopen them or add new ones 👍

2021-06-23 16:54 UTC, theffc commented on content/en/overview.md
> +There are other components with the *children* attribute (or sometimes just *child*) like [Screen]({{< ref path="api/screen/_index.md" >}}) and [ListView]({{< ref path="api/components/layout/listview
Personally, I prefer using ["Oxford's commas"](https://en.wikipedia.org/wiki/Serial_comma), but if that's not the pattern being used throughout our documentation, we can definitely change it here

2021-06-24 14:04 UTC, jessica-tw reviewed
TW review: done ;)

2021-06-24 14:04 UTC, jessica-tw commented on content/en/overview.md
> +- **SwiftUI and Compose:** we will try to support them in the future
```suggestion
- **Android:** [![Maven Central](https://img.shields.io/maven-central/v/br.com.zup.beagle/android)](https://mvnrepository.com/artifact/br.com.zup.beagle/android);
- **iOS:** [![badge](https://img.shields.io/cocoapods/v/Beagle)](https://cocoapods.org/pods/Beagle)
- **React Native:** [![react native badge](https://img.shields.io/npm/v/@zup-it/beagle-react-native?logo=React)](https://www.npmjs.com/package/@zup-it/beagle-react-native);
- **Flutter:** *It is being developed, check out more information [in this folder](https://github.com/ZupIT/beagle/tree/master/flutter)*;
```

2021-06-24 14:44 UTC, igorgiumellizup commented on content/en/overview.md
> +- **Easily test new business hipothesis or make important fixes on live applications** to rapidly improve users experience and receive feedbacks
O que acha de omitirmos um pouco as palavras "you" e "your"? Lendo as docs em inglês da uma canseira de tanto que aparece heheeh

2021-06-24 18:05 UTC, theffc commented on content/en/overview.md
> +The best way to understand how Beagle works is to see it in action. Here, we will show you a simple screen declared via Beagle, containing just texts, images, and some style configurations. At the en
@jessica-tw Do you think "The best way to understand Beagle is to see it in action" would be ok?
Because I wanted to sound like we are going to provide an actual example to our readers

2021-06-24 18:54 UTC, theffc commented on content/en/overview.md
> +- **Easily test new business hipothesis or make important fixes on live applications** to rapidly improve users experience and receive feedbacks
If we stick with "you can" on each list item, we should probably change the previous sentence: 

```txt
By using Beagle, developers can: 
- ...
```

2021-06-24 19:03 UTC, theffc commented on content/en/overview.md
> +- **Easily test new business hipothesis or make important fixes on live applications** to rapidly improve users experience and receive feedbacks
I can't say about other places on our doc, but here I would say I prefer without using "you can" on each item because it seems redundant. But I can also see that it sounds better on some.

2021-06-24 20:33 UTC, igorgiumellizup commented on content/en/overview.md
> +- **Easily test new business hipothesis or make important fixes on live applications** to rapidly improve users experience and receive feedbacks
Suggestions to avoid you / your:
"You can rapidly change... " => "It's possible to rapidly change..."
"By using Beagle, you can:" => "By using Beagle, it's possible:"
"Put this in your BFF..." => "Put this in the/a BFF"
"You need to configure your build.gradle file" => "Configure the build.gradle file"
"Throughout our documentation, you will see examples..." => "Throughout the documentation, there are examples..."

There's always a way to convert you/your to something else, and I don't think it is necessary to include you/your all the time. And it becomes a little informal, considering the Documentation context.

2021-06-28 18:35 UTC, theffc commented
@jessica-tw Thanks a lot for your review! 😊
I grouped the changes in this commit [66c5e1d](https://github.com/ZupIT/beagle-docs/pull/651/commits/66c5e1d454ae44500f66534a95f2380b96eb227d), and feel free to further review them if you want.

Also, I was wondering what you thought about the overall change of this page. Would you say it is better now, or do you prefer as it was before?

2021-06-29 14:29 UTC, carlossteinzup submitted a review, later dismissed

2021-06-29 15:11 UTC, uziasferreirazup approved these changes

2021-06-29 16:04 UTC, igorgiumellizup approved these changes

2021-06-29 17:51 UTC, uziasferreirazup approved these changes

2021-06-29 17:52 UTC, uziasferreirazup requested changes
adjust in pt-br

2021-06-29 20:09 UTC, jessica-tw commented on content/en/overview.md
> +- **Easily test new business hipothesis or make important fixes on live applications** to rapidly improve users experience and receive feedbacks
Claro, tem outras formas. Vou sugerir outra, por exemplo

You are able to:  
**Change an application layout, data, navigation flow, or even logic**, just change the code in your backend.
- **You don't have to depend on mobile stores** like App Store and Play Store because most changes won't need an app update.
- **Applications will behave similarly on different platforms** since the code will be shared and standardized between backend and frontend.
- **Test a new business hypothesis or make important fixes on live applications** to improve users' experience and receive feedback.

2021-06-29 20:35 UTC, jessica-tw commented on content/en/overview.md
> +The best way to understand how Beagle works is to see it in action. Here, we will show you a simple screen declared via Beagle, containing just texts, images, and some style configurations. At the en
Ah ok, I got it. I don't see this expression very often, but if you guys are used to it, just keep it. There are other ways to say it too if you want more options: 
- The best way to understand Beagle is to see how it works in a live example. 
- The best way to understand Beagle is to see how it works in action.

2021-06-29 20:37 UTC, jessica-tw commented
> @jessica-tw Thanks a lot for your review! 😊
> I grouped the changes in this commit [66c5e1d](https://github.com/ZupIT/beagle-docs/pull/651/commits/66c5e1d454ae44500f66534a95f2380b96eb227d), and feel free to further review them if you want.
> 
> Also, I was wondering what you thought about the overall change of this page. Would you say it is better now, or do you prefer as it was before?

Anytime ;), well I think it is better, it is more detailed. If you need help to translate to PT, let me know. @theffc

2021-06-29 23:12 UTC, theffc commented
@jessica-tw I just uploaded the portuguese part, and made some changes in english. Please, take a look if possible 🙂

2021-06-29 23:18 UTC, theffc commented on content/pt/overview.md
> +      "alignItems": "CENTER",
@luisgustavozup @carlossteinzup let me ask you one thing 😅: 

when creating the portuguese page, should I declare the playground's json again, or is there a way to use the one declared in the english page?

2021-06-30 13:46 UTC, uziasferreirazup commented on content/pt/overview.md
> +      "alignItems": "CENTER",
we usually put the same example json on the page en and it will keep the same.
so yes you need to literally replicate everything from the page to en.

2021-06-30 23:52 UTC, uziasferreirazup submitted a review, later dismissed

2021-07-01 12:07 UTC, igorgiumellizup submitted a review, later dismissed

2021-07-01 13:02 UTC, igorgiumellizup approved these changes

2021-07-01 13:38 UTC, uziasferreirazup approved these changes

2021-07-01 14:09 UTC, theffc commented
I'll merge it for now, but feel free to leave more comments and suggestions here. Thank you all for the feedbacks! 😊

2021-07-01 14:09 UTC, merged