fix: Customization Custom Action
ZupIT/beagle-docs pull request #653
Opened 2021-06-21 14:17 UTC by luisgustavozup

Customization Custom Action

2021-06-23 13:35 UTC, igorgiumellizup requested changes

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +Now, with the action ready to run asynchronously, we have to **MUST** notify when its execution is complete by executing the `onFinish` action.
```suggestion
Now, with the action ready to run asynchronously, we **MUST** notify when its execution is complete by executing the `onFinish` action.
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +Your action is now configured to perform any work asynchronously!
```suggestion
Your action is now configured to perform any tasks asynchronously!
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +To learn how to register and use this new action and see step 3 and 4 of the example [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}).
```suggestion
To learn how to register and use this new action, see step 3 and 4 of the example [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}).
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/custom-action.md
> +- How to Register an Action.
```suggestion
- How to Register an Action
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/custom-action.md
> +To see standard beagle actions [**Action types.**]({{< ref path="/api/actions/overview#action-types" lang="en">}})
```suggestion
Standard beagle actions: [**Action types.**]({{< ref path="/api/actions/overview#action-types" lang="en">}})
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/custom-action.md
> +It is mandatory to register actions on Beagle. Inside the beagle config file use dependencies to register.
Where is this 'beagle config file'? An example would be nice!

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/custom-action.md
> +The register method has two constructors, the first passing just the `action` and the second receiving the `action` and `named`.
```suggestion
The register method has two constructors; the first receives just the `action` param and the second receives the `action` and `named` params.
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/custom-action.md
> +**named:** Parameter to set the action name. It is not mandatory to pass. One case is when the action name is registered differently than what you created in the backend. It will be used in deseriali
```suggestion
**named:** Parameter to set the action name. It is not mandatory to inform it, however, you might need it when the action name is registered differently than what you created in the backend. In this case, the parameter will be used in deserializations to find your action.
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/custom-action.md
> +**named:** Parameter to set the action name. It is not mandatory to pass. One case is when the action name is registered differently than what you created in the backend. It will be used in deseriali
Please, confirm that my suggestion makes sense considering the Beagle logic

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/custom-action.md
> +After registering your customization component, you can use it via server-driven.
I think this sentence is a little vague. Is it possible to give more details on how to use it via server-driven?

2021-06-23 13:35 UTC, igorgiumellizup commented on content/en/ios/customization/custom-actions/custom-action.md
> +To use the beagle's actions, the component you are going to use just has a parameter of the type `Action`.
```suggestion
To use the Beagle's actions, the component you are going to use just needs a parameter of the type `Action`.
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/async-custom-action.md
> + - Ter passado pelo exemplo [**Ação Customizada**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="pt" >}}).
```suggestion
 - Ler o exemplo [**Ação Customizada**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="pt" >}}).
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/async-custom-action.md
> +Se não conhece o que é uma ação [**O que é uma ação?**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="pt" >}}).
```suggestion
[**O que é uma ação?**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="pt" >}}).
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/async-custom-action.md
> +Para criar uma ação customizada no Beagle cuja execução seja assíncrona como o consumo de uma API ou acesso a um banco de dados, basta criar uma `action` normalmente como o exemplo [**Ação Customizad
```suggestion
Para criar uma ação customizada no Beagle cuja execução seja assíncrona, como o consumo de uma API ou acesso a um banco de dados, basta criar uma `action` normalmente, como o exemplo [**Ação Customizada**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="pt" >}}) e implementar a interface `AsyncAction`.
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/async-custom-action.md
> +Com a action criada, basta vincular a interface `AsyncAction` interface solicitará que o método execute e o parâmetro onFinish seja implementado.
Esta frase ficou um pouco confusa

2021-06-23 13:35 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/async-custom-action.md
> +Agora, com a action pronta para executar de forma assincrona, temos que **OBRIGATORIAMENTE** notificar quando sua execução está concluída execultando a ação `onFinish`.
```suggestion
Agora, com a action pronta para executar de forma assíncrona, temos que **OBRIGATORIAMENTE** notificar quando sua execução está concluída executando a ação `onFinish`.
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/async-custom-action.md
> +Veja no exemplo da Custom Action Assíncrona.
Seria o exemplo abaixo? Se sim, sugiro "Veja o exemplo abaixo:"

2021-06-23 13:35 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/custom-action.md
> +- Como Registrar uma ação.
```suggestion
- Como registrar uma ação.
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/custom-action.md
> +No Beagle, uma ação lida com os comportamentos (funções), que serão executadas em sua aplicação assim que um determinado evento for disparado. Essas ações podem ser padrão do próprio Beagle ou custom
```suggestion
No Beagle, uma ação lida com os comportamentos (funções) que serão executadas em sua aplicação assim que um determinado evento for disparado. Essas ações podem ser padrão do próprio Beagle ou customizadas.
```

2021-06-23 13:35 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/custom-action.md
> +Para ver ações padrões do beagle, [**tipos de ações.**]({{< ref path="/api/actions/overview#tipos-de-ações" lang="pt">}})
```suggestion
[**Tipos de ações do Beagle**]({{< ref path="/api/actions/overview#tipos-de-ações" lang="pt">}})
```

2021-06-24 12:51 UTC, carlossteinzup commented on content/en/ios/customization/_index.md
> +  You will find here the main classes that are part of Beagle's framework for
```suggestion
  This section lists the main classes that are part of Beagle's framework for iOS
```

2021-06-24 12:52 UTC, carlossteinzup commented on content/en/ios/customization/_index.md
> +These are Beagle for iOS classes:
```suggestion
These are the iOS classes for Beagle
```

2021-06-24 12:52 UTC, carlossteinzup commented on content/en/ios/customization/custom-actions/_index.md
> +  In this section, you will find the description of how to create a custom action and
```suggestion
  In this section, you will find the description on how to create a custom action and
```

2021-06-24 12:55 UTC, carlossteinzup commented on content/en/ios/customization/custom-actions/_index.md
> +In Beagle, an action deals with the behaviors (functions) that will be executed in your application as soon as a certain event is triggered. These actions can be Beagle's own standard or custom actio
```suggestion
An action in Beagle is a function that will be executed in your application when a certain event is triggered. Beagle Actions can be either **default** or **custom**
```

2021-06-24 12:56 UTC, carlossteinzup commented on content/en/ios/customization/custom-actions/async-custom-action.md
> + - Have a project already set up with Beagle.
```suggestion
 - Have a project set up with Beagle.
```

2021-06-24 13:26 UTC, carlossteinzup commented on content/en/ios/customization/custom-actions/async-custom-action.md
> + - Having passed by example [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}).
```suggestion
 - Have done the example for [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}).
```

2021-06-24 13:30 UTC, carlossteinzup commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +If you don't know what an action is [**What is an action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="pt" >}}).
```suggestion
If you don't know what an action is, check the [**What is an action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="pt" >}}) section.
```

2021-06-24 13:52 UTC, carlossteinzup commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +To create a custom action in Beagle whose execution is asynchronous like consuming an API or accessing a database, just create an `action` normally like the example [**Custom Action**]({{< ref path="
```suggestion
To create an asynchronous custom action in Beagle that works like an API just create an `action` normally like the example in [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}) and implement the `AsyncAction` interface.
```

2021-06-24 14:03 UTC, carlossteinzup commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +Now, with the action ready to run asynchronously, we **MUST** notify when its execution is complete by executing the `onFinish` action.
```suggestion
Now we **MUST** notify when its execution is completed by triggering the `onFinish` action.
```

2021-06-24 14:04 UTC, carlossteinzup commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +See the Asynchronous Custom Action example.
```suggestion
Here follows an Asynchronous Custom Action example.
```

2021-06-24 14:06 UTC, carlossteinzup commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +To learn how to register and use this new action, see step 3 and 4 of the example [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}).
```suggestion
To learn how to register and use a new action, see step 3 and 4 of the example [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}).
```

2021-06-24 14:07 UTC, carlossteinzup commented on content/en/ios/customization/custom-actions/custom-action.md
> +description: Creating and running a custom action
```suggestion
description: This sections lists how to create and trigger a custom action
```

2021-06-25 17:25 UTC, luisgustavozup commented on content/en/ios/customization/custom-actions/custom-action.md
> +It is mandatory to register actions on Beagle. Inside the beagle config file use dependencies to register.
Tem um link abaixo direcionado para a parte de configuração.

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/async-custom-action.md
> + - Have done the example for [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}).
```suggestion
 -  A project set up with Beagle.
 - You need to have done the example for [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}).
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +After creating an action, you must implement the `AsyncAction` interface. That will request that an execute method and the onFinish parameter are implemented.
```suggestion
After creating an action, you must implement the `AsyncAction` interface. It will request to execute a method and the onFinish parameter will be implemented.
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +
```suggestion
Now you **MUST** notify when its execution is completed by triggering the `onFinish` action.

```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/async-custom-action.md
> +To learn how to register and use a new action, check the steps 3 and 4 on the [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}) example.
```suggestion
To learn how to register and use a new action, check the steps 3 and 4 in the [**Custom Action**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="en" >}}) example.
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> + - Have a project already set up with Beagle.
```suggestion
 -You need a project already set up with Beagle.
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> +### **Step 1: What is an action**
```suggestion
### **Step 1: What is an action?** 
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> +### **Step 2: How to create a custom action:**
```suggestion
### **Step 2: How to create a custom action?**
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> +As an action logic, let's create an alert. Below is an example of the alert.
```suggestion
As an action logic, you have to create an alert. See an example below:

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> +Finally, just create the parameter to receive the alert message, and the init of the struct.
```suggestion
Now, you have to add the action logic inside the `execute` method. Then, create the parameter to receive the alert message and the init of the struct.
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> +It is mandatory to register actions on Beagle. Inside the beagle config file use dependencies to register.
```suggestion
### **Step 3: How to Register an Action?**

It is mandatory to register actions on Beagle. To do that, go inside the beagle config file and use the dependencies to register.
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> +Ways to Register
```suggestion
Check out below, the ways you can register: 
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> +1º The first way to register.
```suggestion
**- The first way to register:**
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> +2º The second way to register.
```suggestion
**- The second way to register:**
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> +### **Step 3: How to use an action**
```suggestion
### **Step 3: How to use an action?**
```

2021-07-05 13:40 UTC, jessica-tw commented on content/en/ios/customization/custom-actions/custom-action.md
> +Below is an example of how to use it on a button that performs the custom action on the click event:
```suggestion
To use Beagle's actions, the component you are going to use needs a parameter of the `Action` type.

Check out an example below on how to use it on a button that performs the custom action on the click event:
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/async-custom-action.md
> +{{% /alert %}}
```suggestion
{{% alert color="info" %}}
Veja mais sobre [**O que é uma ação?**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="pt" >}}).
{{% /alert %}}
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/async-custom-action.md
> +Com a action criada, basta vincular a interface `AsyncAction` interface solicitará que o método execute e o parâmetro onFinish seja implementado.
```suggestion
Depois de criar a action, agora você deve vincular a interface `AsyncAction` interface que solicitará que o método execute e o parâmetro onFinish seja implementado.
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/async-custom-action.md
> +Agora, com a action pronta para executar de forma assíncrona, temos que **OBRIGATORIAMENTE** notificar quando sua execução está concluída executando a ação `onFinish`.
```suggestion
Agora, com a action pronta para executar de forma assíncrona, você deve **OBRIGATORIAMENTE** notificar quando sua execução está concluída e para isso execute a ação `onFinish`.
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/custom-action.md
> +[**Tipos de ações do Beagle**]({{< ref path="/api/actions/overview#tipos-de-ações" lang="pt">}})
```suggestion
Veja mais sobre os [**Tipos de ações do Beagle**]({{< ref path="/api/actions/overview#tipos-de-ações" lang="pt">}})
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/custom-action.md
> +
```suggestion
### **Passo 2: Como criar uma ação customizada?**

```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/custom-action.md
> +Como lógica da ação vamos criar um alert. Abaixo temos o exemplo do alert.
```suggestion
Como lógica da ação é preciso criar um alert, veja abaixo um exemplo:
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/custom-action.md
> +Por fim, basta criar o parametro para receber a mensagem do alert, e o init da struct.
```suggestion
Agora adicione a lógica da ação dentro do método `execute`. Depois crie o parâmetro para receber a mensagem do alert, e o init da struct.
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/custom-action.md
> +### **Passo 3: Como Registrar uma ação.**
```suggestion
### **Passo 3: Como registrar uma ação?**
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/custom-action.md
> +
```suggestion
É obrigatório registrar ações no Beagle. E para fazer isso, acesse dentro do arquivo de configuração do Beagle e utilize o dependencies para registrar.

```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/custom-action.md
> +1º A primeira maneira de registrar.
```suggestion
Veja abaixo as formas que você pode registrar:

**- A primeira forma:**
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/custom-action.md
> +2º A segunda maneira de registar.
```suggestion
**- A segunda forma:** 
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/custom-action.md
> +Para usar as ações do beagle basta o componente que for usar ter um parametro do tipo `Action`.
```suggestion
Para usar as ações do Beagle, o componente que você for utilizar precisa de um parâmetro do tipo `Action`.
```

2021-07-05 13:40 UTC, jessica-tw commented on content/pt/ios/customization/custom-actions/overview.md
> +Para ver ações padrões do beagle, [**tipos de ações.**]({{< ref path="/api/actions/overview#tipos-de-ações" lang="pt">}})
```suggestion
Para ver ações padrões do Beagle, acesse os [**tipos de ações.**]({{< ref path="/api/actions/overview#tipos-de-ações" lang="pt">}})
```

2021-07-06 12:12 UTC, igorgiumellizup requested changes

2021-07-06 12:12 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/async-custom-action.md
> +Para criar uma ação customizada no Beagle cuja execução seja assíncrona, como o consumo de uma API ou acesso a um banco de dados, basta criar uma `action` normalmente, como o exemplo [**Ação Customiz
```suggestion
Para criar uma ação customizada no Beagle cuja execução seja assíncrona, como o consumo de uma API ou acesso a um banco de dados, basta criar uma `action` como no exemplo [**Ação Customizada**]({{< ref path="/ios/customization/custom-actions/custom-action" lang="pt" >}}) e implementar a interface `AsyncAction`.
```

2021-07-06 12:12 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/custom-action.md
> +Como lógica da ação vamos criar um alert. Abaixo temos o exemplo do alert.
@luisgustavozup é **preciso** mesmo criar um alert, ou é apenas um exemplo?

2021-07-06 12:12 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/custom-action.md
> +**action:** Passa a struct da action.
```suggestion
**action:** Struct da action.
```

2021-07-06 12:12 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/custom-action.md
> +**named:** Parâmetro para setar o nome da action. Não é obrigatório passar. Um caso é quando o nome da action é registrado diferente com que você criou no backend. Ele será usado na deserializações p
```suggestion
**named:** Nome da action, não obrigatório. Utiliza-se, por exemplo, quando o nome da action registrada é  diferente da criada no backend. Ele será usado na deserializações para encontrar a ação.
```

2021-07-06 12:12 UTC, igorgiumellizup commented on content/pt/ios/customization/custom-actions/custom-action.md
> +**named:** Parâmetro para setar o nome da action. Não é obrigatório passar. Um caso é quando o nome da action é registrado diferente com que você criou no backend. Ele será usado na deserializações p
@luisgustavozup se concordar com essa sugestão, peço que considere revisar outras que seguem o mesmo padrão.

2021-07-14 13:39 UTC, merged