refactor: updates the text input info, attribute details and table structure main
ZupIT/beagle-docs pull request #692
Opened 2021-06-29 21:41 UTC by carlossteinzup

refactor: updates the text input info, attribute details and table structure main

2021-06-30 13:44 UTC, uziasferreirazup requested changes

2021-06-30 13:44 UTC, uziasferreirazup commented on content/en/api/components/ui/textinput.md
> +{{% /alert %}}
I believe that this type of warning should not be on the component but on the action page, otherwise you will need to put the same comment in each component and it will not add value to the user, as he is wanting to know about the component itself and not of action.
 The same comment to page in PT-BR

2021-06-30 19:28 UTC, carlossteinzup commented on content/en/api/components/ui/textinput.md
> +{{% /alert %}}
```suggestion
```

2021-06-30 19:29 UTC, carlossteinzup commented on content/pt/api/components/ui/textinput.md
> +Importante! O Beagle também oferece suporte para ações customizadas ou seja, se você listar alguma delas nos atributos acima, também precisará mapeá-las em seu front end. Você não precisa fazer isso
```suggestion
```

2021-06-30 23:51 UTC, uziasferreirazup approved these changes

2021-07-01 13:58 UTC, uziasferreirazup approved these changes

2021-07-01 13:58 UTC, merged