refactoring beagle-helpers
ZupIT/beagle-docs pull request #716
Opened 2021-07-15 18:40 UTC by jacoabreuzup

Beagle-helpers refactored on iOS.

2021-07-16 18:31 UTC, igorgiumellizup requested changes
@jacoabreuzup eu revisei até um certo ponto, pois percebi que certos erros se repetiam, então se puder pegar o aprendizado das sugestões / correções que propus e aplicar no restante eu agradeço!

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-defaults.md
> +description: 'This framework provides default implementations of a Network client, Cache control and Logger that can be easily embedded and used in your Beagle project.'
```suggestion
description: 'This framework provides default implementation of network client, cache control and logger. That implementation is easily embedded and used in your Beagle project.'
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-defaults.md
> +* What is?
```suggestion
* What is it?
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-defaults.md
> +### What is?
```suggestion
### What is it?
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-defaults.md
> +It's a lib that contains default implementations of a Network layer, Cache manager and Log system. It can be used by Beagle users that do not want to implement this layers from scratch.
```suggestion
It's a lib that contains default implementations of network layer, cache management and log system. It can be used by Beagle users that do not want to implement these layers from scratch.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-defaults.md
> +After adding BeagleDefaults as a dependency in your project, you can use all the default implementations in your `Beagle.dependencies`.
```suggestion
After adding BeagleDefaults as a dependency in your project, you can use all the default implementation in your `Beagle.dependencies`.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-defaults.md
> +All implementations can be changed up to your preferences. It's still not recommended to use this implementations without checking your product guidelines of security, cache management and log system
```suggestion
All implementation can be changed up to your preferences. It's still not recommended to use mentioned implementation without checking your product' security guidelines, its cache management and log system.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-defaults.md
> +##### For more on Beagle: Please check our [Beagle](https://github.com/ZupIT/beagle) repository.
```suggestion
##### More about Beagle: https://github.com/ZupIT/beagle
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-defaults.md
> +##### For more on Beagle-Scaffold: Please check our [Beagle-Scaffold]({{< ref path="/get-started/using-beagle-helpers/ios/beagle-scaffold" lang="en" >}}) documentation.
```suggestion
##### More about Beagle-Scaffold: check out our [Beagle-Scaffold]({{< ref path="/get-started/using-beagle-helpers/ios/beagle-scaffold" lang="en" >}}) documentation.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +description: 'Here you will find the **Beagle Scaffold** library that will help you start a project using Beagle in iOS. It holds almost all necessary configurations to do it.'
```suggestion
description: Here you will find the **Beagle Scaffold** library that will help you start a project using Beagle in iOS. It contains almost all necessary configurations to do it.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +* What is?
```suggestion
* What is it?
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +### What is?
```suggestion
### What is it?
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +Beagle Scaffold is a supporting framework that has default implementations of a Network layer, Cache and Logger for you, embedded in [BeagleDefaults](https://docs.usebeagle.io/get-started/using-beagl
```suggestion
Beagle Scaffold is a supporting framework that has default implementation of network layer, cache and logger, all embedded in [BeagleDefaults](https://docs.usebeagle.io/get-started/using-beagle-helpers/ios/beagle-defaults), so you can start using Beagle faster.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +**Step 1:** To start configuring Beagle on our app, we need to go into the file SceneDelegate, then import the lib `BeagleScaffold` and call our function named `start()` from Beagle Scaffold's class
```suggestion
**Step 1:** To start configuring Beagle in our app, we need to go into the file SceneDelegate, then import the lib `BeagleScaffold` and call the function named `start()` from Beagle Scaffold's class `BeagleConfig`, inside method `scene()`:
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +**Step 2:** Now we need to do our project initialization using a View Code approach:
```suggestion
**Step 2:** Now we need to initialize the project using a View Code approach:
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +1. Still in the method `scene`, give the name `windowScene` to the `guard let` already created for us by Xcode:
```suggestion
1. Still in the method `scene`, name `windowScene` to `guard let`:
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +2. Initialize the variable `window` created outside the function scope, using our `windowScene`:
```suggestion
2. Initialize the variable `window` created outside the function scope, using `windowScene`:
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +3. Make the `window?.rootViewController` our `BeagleScaffoldDemoViewController` and call the method `makeKeyAndVisible()`. Your code should be like this:
```suggestion
3. Make the `window?.rootViewController` become `BeagleScaffoldDemoViewController` and call the method `makeKeyAndVisible()`. Your code should be like this:
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +**Step 3:** Run your project, and you should see a sample screen with all Beagle components on your simulator.
```suggestion
**Step 3:** Run your project, and you should see a sample screen with all Beagle components on the simulator.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +In this section you will learn on how to customize your Beagle Scaffold. Let's start with the most basic and common one: changing your base Url. This will happen when you try rendering your first ser
```suggestion
In this section you will learn on how to customize your Beagle Scaffold. Let's start with the most basic and common one: changing the base Url. This will happen when you try rendering your first server-driven screen, which will be right after displaying our demo screen.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +3. Inside our `setup` function, instantiate a variable `dependencies` that is a `BeagleDependencies`.
```suggestion
3. Inside the `setup` function, instantiate a variable called `dependencies` that is a `BeagleDependencies`.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +4. Change the property `urlBuilder` of our variable to match your base Url. In this example we'll be using a localhost url, such as `http://localhost:8080`.
```suggestion
4. Change the property `urlBuilder` to match the base URL. In this example, we'll be using a localhost url, such as `http://localhost:8080`.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +5. Now you need to notify Beagle that you changed this property. To do that just pass your `dependencies` variable as a parameter for the `start` method from BeagleScaffold's `BeagleConfig`.
```suggestion
5. Now you need to notify Beagle that you changed this property. To do that, just pass your `dependencies` variable as a parameter to the `start` method from BeagleScaffold's `BeagleConfig`.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +**Step 2:** Now we need to change our `SceneDelegate` class. Inside the method `scene`, you'll no longer call `BeagleConfig.start()`. You'll call `BeagleConfigurations.setup()` instead. You can see y
```suggestion
**Step 2:** Now we need to change the `SceneDelegate` class. Inside the method `scene`, you'll no longer call `BeagleConfig.start()`. Call `BeagleConfigurations.setup()` instead. You can see your screen by giving an endpoint to a `BeagleScreenViewController`, but you need to import Beagle first. Then you can use this controller as your new `window?.rootViewController` like this:
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +**Step 3:** Since your endpoint will probably not be a secure connection, you will need to allow an arbitrary loads on your `info.plist` file. Go into it, and create a property `App Transport Securit
```suggestion
**Step 3:** Since your endpoint will probably not be a secure connection, you will need to allow an arbitrary load in your `info.plist` file. To do this, create a property called `App Transport Security Settings` by clicking on the `+` icon at the `Information Property List` level. At the `App Transport Security Settings` level, click on the `>` icon to open it up, then create the property `Allow Arbitrary Loads` and set it to `YES`.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +Cool! Now you can see your own server-driven screen!
Can we be that informal in a doc?

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +As you have seen, Beagle Scaffold is a lib for supporting newer people to Beagle, helping them rendering a screen using Beagle as fast as they can.
```suggestion
As you have seen, Beagle Scaffold is a lib for supporting newcomers to Beagle, helping them rendering a screen using Beagle as fast as possible.
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +But as you also have seen, you can customize Beagle Scaffold to match your needs. We've seen that we can easily change our endpoint, to see a new screen instead of Beagle Scaffold's demo, and you can
```suggestion
You can customize Beagle Scaffold to match your needs. We've seen that we can easily change our endpoint to render a new screen instead of Beagle Scaffold's demo, and you can already guess that you can customize basically every Beagle property inside Beagle dependencies. 
```

2021-07-16 18:31 UTC, igorgiumellizup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +And there is a set of properties that you can and you should customize, which is the NetworkClient, CacheManager and Logger. If your app is going to production it's essential to determine your securi
```suggestion
And there is a set of properties that you can and you should customize, which is the NetworkClient, CacheManager and Logger. If your app is going to be delivered to production, it's essential to configure your security levels, your cache management and what information you want to log.
```

2021-07-19 13:15 UTC, jacoabreuzup commented on content/en/ios/beagle-helpers/beagle-defaults.md
> +* What is?
That was a major flaw in my english haha

2021-07-19 13:23 UTC, jacoabreuzup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +Cool! Now you can see your own server-driven screen!
How informal? I mean, I think there is no other way to ask the user to create that propertie in info.plist, because it's a little bit trick to do it

2021-07-19 13:38 UTC, jacoabreuzup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +1. Still in the method `scene`, give the name `windowScene` to the `guard let` already created for us by Xcode:
I don't know if I understood correctly, but in this case you're saying to name windowScene with guard let? In this case it should give a name to the guard let that it's already there, with the name windowScene. Does it make sense to still make this change?

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-defaults.md
> +##### Para mais sobre Beagle-Scaffold: por favor cheque a nossa documentação [Beagle-Scaffold]({{< ref path="/get-started/using-beagle-helpers/ios/beagle-scaffold" lang="en" >}}).
```suggestion
##### Para saber mais sobre Beagle, acesse o repositório [Beagle](https://github.com/ZupIT/beagle).
##### Para mais sobre Beagle-Scaffold, veja a [seção Beagle-Scaffold]({{< ref path="/get-started/using-beagle-helpers/ios/beagle-scaffold" lang="en" >}}).
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-defaults.md
> +Todas as implementações podem ser alteradas de acordo com suas preferências. Ainda não é recomendado usar essas implementações sem verificar as diretrizes de segurança do produto, gerenciamento de ca
```suggestion
Depois de adicionar BeagleDefaults como uma dependência em seu projeto, você pode usar todas as implementações padrão em seu `Beagle.dependencies`.

Essas implementações podem ser alteradas de acordo com suas preferências. Verifique as diretrizes de segurança do seu produto como gerenciamento de cache e sistema de log antes de implementar. 
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/overview.md
> +description: 'Aqui você vai encontrar bibliotecas de apoio para criar projetos iOS usando o Beagle. Essas bibliotecas vão facilitar a configuração inicial do Beagle em um projeto, pulando alguns pass
```suggestion
description: 'Nesta seção, você encontra as bibliotecas de apoio para criar projetos iOS usando o Beagle.'
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/overview.md
> +{{% /alert %}}
```suggestion
---
Essas bibliotecas facilitam a configuração inicial do Beagle no seu projeto.  Veja abaixo: 

![Cocoapods](https://img.shields.io/cocoapods/v/BeagleScaffold?label=Beagle-Scaffold)
![Cocoapods](https://img.shields.io/cocoapods/v/BeagleDefaults?label=Beagle-Defaults)
![Cocoapods](https://img.shields.io/cocoapods/v/Beagle?label=Beagle)

* [Beagle-Scaffold]({{< ref path="/get-started/using-beagle-helpers/ios/beagle-scaffold" lang="en" >}}):
Contém quase todas as configurações necessárias pra começar a usar o Beagle no seu projeto. Recomendado para usuários iniciantes de Beagle.

* [Beagle-Defaults]({{< ref path="/get-started/using-beagle-helpers/ios/beagle-defaults" lang="en" >}}):
Essa biblioteca é indicada para usuários mais avançados do Beagle e possui apenas algumas configurações de classes necessárias para utilizar o Beagle na sua aplicação. Elas incluem uma camada padrão de rede, cache e log e também estão disponíveis no Beagle Scaffold.

{{% alert color="warning" %}}
Se você deseja configurar um projeto do zero com o Beagle,  veja a [**seção 'Criando um projeto do zero'**]({{< ref path="/get-started/creating-a-project-from-scratch/case-ios/" lang="en" >}})
{{% /alert %}}
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +**Passo 2**: No seu terminal, rode o comando `pod init` para criar um Podfile e adicione o Beagle Scaffold como uma dependência do seu projeto. Como a seguir:
```suggestion
**Passo 2**: No seu terminal, rode o comando `pod init` para criar um Podfile e adicione o Beagle Scaffold como uma dependência do seu projeto. Como no exemplo abaixo:
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +Se você não é familiarizado com o Cocoapods, dê uma checada na [documentação](https://guides.cocoapods.org/) deles.
```suggestion
Para mais informações sobre o Cocoapods, acesse a [**documentação**](https://guides.cocoapods.org/). 
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +**Passo 3:** Rode o comando `pod install` para instalar o Beagle Scaffold no seu app. Esse comando vai gerar um Workspace. A partir de agora você vai usar apenas o Workspace.
```suggestion
**Passo 3:** Rode o comando `pod install` para instalar o Beagle Scaffold no seu app. Esse comando gera um Workspace e partir de agora é o que você irá utilizar. 
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +**Passo 1:** Para começar a configurar o Beagle em nosso aplicativo, precisamos ir para o arquivo SceneDelegate, importar a lib `BeagleScaffold` e chamar nossa função chamada `start` da classe do Bea
```suggestion
### Configurações
<hr>
Para começar a configurar o Beagle no seu aplicativo, siga os passos: 

**Passo 1:** Acesse o arquivo SceneDelegate, importe a lib `BeagleScaffold` e chame a função  `start` da classe do Beagle Scaffold `BeagleConfig`, dentro do método `scene`:
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +1. Ainda no método `scene`, dê o nome `windowScene` para o `guard let` já criado para nós pelo Xcode:
```suggestion
**Passo 2:** Faça a inicialização do projeto usando uma abordagem View Code, veja como abaixo:

1. Ainda no método `scene`, dê o nome `windowScene` para o `guard let` já criado pelo Xcode:
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +2. Inicialize a variável `window` criada fora do escopo da função, usando a nossa `windowScene`:
```suggestion
2. Inicialize a variável `window` criada fora do escopo da função, usando a `windowScene`:
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +3. Faça o `window?.rootViewController` o nosso `BeagleScaffoldDemoViewController` e chame o método `makeKeyAndVisible`. Seu código deveria estar assim:
```suggestion
3. Faça o `window?.rootViewController` o `BeagleScaffoldDemoViewController` e chame o método `makeKeyAndVisible`. Seu código deve estar assim:
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +**Passo 3:** Rode o seu projeto e você deve ver uma tela com todos os componentes do Beagle no seu simulador.
```suggestion
**Passo 3:** Rode o seu projeto para ver uma tela com todos os componentes do Beagle no seu simulador.
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +Nessa seção você vai aprender como customizar o seu Beagle Scaffold. Vamos começar com o mais comum e básico: mudança da Url base. Isso vai acontecer quando você tentar renderizar a sua primeira tela
```suggestion
Nessa seção você vai aprender como customizar o seu Beagle Scaffold. 
Começe com o mais comum, a mudança da Url base. Isso vai acontecer quando você tentar renderizar a sua primeira tela server driven, que é logo após a tela demo do Beagle Scaffold.
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +Sua classe `BeagleConfigurations` deveria estar assim:
```suggestion
1. Importe o Beagle e o BeagleScaffold;
2. Crie uma função estática `setup`;
3. Dentro da função `setup`, instancie a variável `dependencies` que é uma `BeagleDependencies`;
4. Mude a propriedade `urlBuilder` da nossa variável para a sua Url base. Nesse exemplo foi utilizado uma url localhost, como `http://localhost:8080`.
5. Agora você precisa notificar o Beagle que você mudou essa propriedade. Para fazer isso passe sua variável `dependencies` como um parâmetro para o método `start` da classe `BeagleConfig` do BeagleScaffold.

Sua classe `BeagleConfigurations` deve estar como o exemplo abaixo: 
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +**Passo 2:** Agora precisamos mudar a nossa classe `SceneDelegate`. Dentro do método `scene`, você não vai mais chamar o método `BeagleConfig.start()`. Você vai chamar agora o `BeagleConfigurations.s
```suggestion
**Passo 2:** Mude a classe `SceneDelegate`. Dentro do método `scene`, você não vai mais chamar o método `BeagleConfig.start()`, mas o `BeagleConfigurations.setup()`. Você pode ver a sua tela passando um endereço para o seu `BeagleScreenViewController`, mas você precisa importar o Beagle antes. 
Você pode usar essa controladora como a sua nova `window?.rootViewController`. Veja o exemplo abaixo: 
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +{{% /alert %}}
```suggestion
**Passo 3:** Como o seu endereço provavelmente não vai ser uma conexão segura, você precisa permitir essa conexão. Para isso, siga: 

1. Vá no seu arquivo `info.plist`;
2. Crie a propriedade `App Transport Security Settings` clicando no ícone `+` no nível de `Information Property List`;
3. Abra o nível `App Transport Security Settings` clicando no ícone `>`, 
4. Crie a propriedade `Allow Arbitrary Loads` e a defina para `YES`.

{{% alert color="success" %}}
Agora você já consegue ver a sua própria tela server-driven! 
{{% /alert %}}
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +Você pode criar um exemplo dessas camadas usando estes tutoriais:
```suggestion
O Beagle Scaffold é uma biblioteca de apoio para novos usuários do Beagle, ajudando-os a renderizar uma tela server driven o mais rápido possível.

Você pode customizar o Beagle Scaffold da maneira que precisar. Você consegue alterar a url base do app e depois passar um novo endpoint para renderizar a sua tela ao invés da tela demo do Beagle Scaffold.
Você pode customizar qualquer propriedade do Beagle dentro das Beagle Dependencies.

Existe um conjunto de propriedades que você deve customizar, como o cliente de rede, o gerenciador de cache e o sistema de log. Se o seu app ir para produção, é essencial determinar os níveis de segurança, o gerenciamento de cache e quais informações pretende logar.

Você pode criar um exemplo dessas camadas usando estes tutoriais:
```

2021-07-19 17:44 UTC, jessica-tw commented on content/pt/ios/beagle-helpers/beagle-scaffold.md
> +##### Para mais sobre Beagle-Defaults: por favor cheque a nossa documentação [Beagle-Default]({{< ref path="/get-started/using-beagle-helpers/ios/beagle-defaults" lang="en" >}}).
```suggestion
##### Para mais informações sobre Beagle, acesse o repositório [Beagle](https://github.com/ZupIT/beagle).
##### Para saber mais sobre Beagle-Defaults, veja a seção [Beagle-Default]({{< ref path="/get-started/using-beagle-helpers/ios/beagle-defaults" lang="en" >}}).
```

2021-07-19 18:51 UTC, jacoabreuzup commented on content/en/ios/beagle-helpers/beagle-scaffold.md
> +* Other Possible Customizations
humm... I don't know if you can assume that everyone is going to see that. But if it is in the flow of the document he will.

2021-07-19 19:52 UTC, igorgiumellizup approved these changes

2021-07-19 20:20 UTC, carlossteinzup approved these changes

2021-07-19 20:20 UTC, merged