feat: add beagle flutter documentation
ZupIT/beagle-docs pull request #717
Opened 2021-07-16 04:45 UTC by matheusribeirozup

This PR adds the documentation for Beagle Flutter.

2021-07-16 15:35 UTC, igorgiumellizup requested changes

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/beagle-widget.md
> +Class used to make requests on Beagle Flutter. It implements the `BeagleNetworkOptions` which brings the `method`, `headers` and `strategy` attributes. Also, the `BeagleScreenRequest` class has the `
```suggestion
Class used to make requests in Beagle Flutter. It implements the `BeagleNetworkOptions` which brings the `method`, `headers` and `strategy` attributes. Also, the `BeagleScreenRequest` class has the `url` and `body` properties. Let's see his structure:
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/beagle-widget.md
> +Wherever you want to show server driven content, just place the `BeagleWidget` there informing at least a local JSON or a `BeagleScreenRequest` with the `url` of your BFF. In the next example, we put
```suggestion
Wherever you want to show a server-driven content, just place the `BeagleWidget` there informing at least a local JSON or a `BeagleScreenRequest` with the `url` of your BFF. In the next example, we put it in the `Scaffold` widget body:
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +The method `BeagleSdk.init` is the entry point to Beagle Flutter and the receiver of all configuration it handles. By default, basic implementations are already provided for some of its parameters, i
```suggestion
The method `BeagleSdk.init` is the entry point to Beagle Flutter and the receiver of all configuration it handles. By default, basic implementation is already provided for some of its parameters, so it's not necessary to configure all of them.
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +Interface that provides a client to Beagle make the requests. Default is `DefaultHttpClient`. This is a key component to Beagle, because it's used in every request even it's implementation is quite s
```suggestion
Interface that provides a client to enable Beagle make the requests. Default is `DefaultHttpClient`. This is a key component to Beagle, because it's used in every request and its implementation is quite simple. Follow below the `HttpClient` contract:
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +This provides a struct where the key is the `_beagleComponent_` property in JSON and the value is the widget that Beagle should render. To use a list of common widgets with basic implementation, use
```suggestion
Provides a struct where the key is the `_beagleComponent_` property in JSON and the value is the widget that Beagle should render. To use a list of common widgets with basic implementation, use the `beagle_components` package in your project. Default is empty map. Here is a example of a component declaration:
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +It handles the cache for requests made by Beagle. Default is `DefaultStorage`. To avoid vulnerability issues, the default implementation stores information only in memory, see below:
```suggestion
It handles the cache for requests made by Beagle. Default is `DefaultStorage`. To avoid vulnerability issues, the default implementation stores information only in memory, as seen in the exemple below:
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +Whether or not to send specific beagle headers in requests to fetch a widget. Default is `true`.
```suggestion
Whether or not to send specific Beagle headers in requests to fetch a widget. Default is `true`.
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +The map of custom actions. The key must be `_beagleAction_` identifier in JSON and the value must be the action handler. Default is `defaultActions` map. Below is a declaration of this property:
```suggestion
The map of custom actions. The key must be a `_beagleAction_` identifier in JSON and the value must be the action handler. Default is `defaultActions` map. Check a declaration of this property below:
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +This property tells Beagle how to handle the requests cache. There are seven caching strategies that Beagle implements. Default is `BeagleNetworkStrategy.beagleWithFallbackToCache`. Below are all of
```suggestion
This property tells Beagle how to handle the requests cache. There are seven caching strategies that Beagle implements. Default is `BeagleNetworkStrategy.beagleWithFallbackToCache`. Check all of them below:
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +Options for the visual feedback when navigating from a widget to another. To set the default options, use `default: true` in the navigation controller. Default is empty map. Below is the declaration
```suggestion
Options for the visual feedback when navigating from a widget to another. To set the default options, use `default: true` in the navigation controller. Default is an empty map. Check below the declaration of a custom `NavigationController`: 
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +Interface that provides design system to Beagle components. This makes available to Beagle images and styles to buttons and texts. Default is `DefaultEmptyDesignSystem` that doesn't return any value.
```suggestion
Interface that provides design system to Beagle components. This enables images, styles, buttons and texts in Beagle. Default is `DefaultEmptyDesignSystem`, that doesn't return any value. Here is the `BeagleDesignSystem` contract:
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +Interface that provides logger to Beagle use in application. Default is `DefaultEmptyLogger` that doesn't log any information. Here is the `BeagleLogger` contract:
```suggestion
Interface that provides logger for Beagle to use in application. Default is `DefaultEmptyLogger` that doesn't log any information. Here is the `BeagleLogger` contract:
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +Just like custom componentes, it's pretty simple to create a custom actions in Beagle Flutter, you need to declare a map that follows the strcut `Map<String, ActionHandler>` and pass it to the initia
```suggestion
Just like custom componentes, it's pretty simple to create a custom action in Beagle Flutter. You need to declare a map that follows the struct `Map<String, ActionHandler>` and pass it to the initialization method `BeagleSdk.init`. Basically, this struct tells Beagle which action to trigger when a given identifier comes from a 
 JSON.
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +The first step to create a custom action with Beagle Flutter, is to define the identifier. Here, let's name it `custom:log`.
```suggestion
The first step to create a custom action with Beagle Flutter is to define the identifier. Here, let's name it `custom:log`.
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +Now create your action regardless of Beagle. For this example, we'll use the simple function below:
regardless of Beagle **what**? action, implementation, interface, lib... ?

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +### Step 4: Pass them to Beagle
```suggestion
### Step 4: Pass the custom map to Beagle
```

2021-07-16 15:35 UTC, igorgiumellizup commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +To Beagle be able to trigger your action, pass the map you just created through the Beagle init method:
```suggestion
For Beagle to be able to trigger your action, pass the map you just created through the Beagle init method:
```

2021-07-16 15:54 UTC, jessica-tw reviewed
English review is done. 
I will review Portuguese later too.

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +Options for the visual feedback when navigating from a widget to another. To set the default options, use `default: true` in the navigation controller. Default is empty map. Below is the declaration
```suggestion
These are the options for visual feedback when navigating from a widget to another. 
To set the default options: 
- Use `default: true` in the navigation controller. 

The default is an empty map. Check out below the declaration of a custom `NavigationController`: 
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +Interface that provides design system to Beagle components. This makes available to Beagle images and styles to buttons and texts. Default is `DefaultEmptyDesignSystem` that doesn't return any value.
```suggestion
An interface that provides a design system to Beagle components. This one makes available to Beagle from images and styles to buttons and texts. 
The default is `DefaultEmptyDesignSystem` that doesn't return any value. Check out the `BeagleDesignSystem` contract:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +Interface that provides image resource from network. This must implement the `downloadImage` method that receives the image url and returns a `Future<Uint8List>` as the image. Default is `DefaultBeag
```suggestion
An interface that provides image resources from the network. This must implement the `downloadImage` method that receives the image URL and returns a `Future<Uint8List>` as the image. 
The default is `DefaultBeagleImageDownloader`. See an example: 
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +Interface that provides logger to Beagle use in application. Default is `DefaultEmptyLogger` that doesn't log any information. Here is the `BeagleLogger` contract:
```suggestion
An interface that provides logger to Beagle use in the application. The default is `DefaultEmptyLogger` that doesn't log any information. See the `BeagleLogger` contract:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/configuration.md
> +The map of custom operations that can be used to extend the capability of the Beagle expressions and are called like functions, e.g. `@{sum(1, 2)}`. Default is empty map.
```suggestion
The map of custom operations can be used to extend the capability of Beagle's expressions and they are called like functions, e.g. `@{sum(1, 2)}`. The default is an empty map.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/_index.md
> +  You will find here information of how to do customizations in Beagle Flutter.
```suggestion
 In this section, you will find information on how to do customizations in Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +  You will find here information of how to create and use your own actions in Beagle Flutter.
```suggestion
In this section, you will find information on how to create and use your own actions in Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +Just like custom componentes, it's pretty simple to create a custom actions in Beagle Flutter, you need to declare a map that follows the strcut `Map<String, ActionHandler>` and pass it to the initia
```suggestion
It's simple to create custom actions in Beagle Flutter, you need to: 
- Declare a map that follows the struct `Map<String, ActionHandler>`; 
- Pass it to the initialization method `BeagleSdk.init`. 

This struct tells Beagle which action trigger when a given identifier comes into JSON.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +The ActionHandler value of the map is a function that receives a `BeagleAction`, a `BeagleView`, a `BeagleUIElement` and a context as parameters, following the strcut `void Function({BeagleAction act
```suggestion
The ActionHandler value of the map is a function that receives a:
1. `BeagleAction`; 
2. `BeagleView`;
3. `BeagleUIElement`;
4.  A context as parameters following the struct `void Function({BeagleAction action, BeagleView view, BeagleUIElement element, BuildContext context})`. 

These parameters are available because they provide all the information needed to trigger an event, such as context and the action coming from JSON.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +Follow this steps to learn how to create and use your own custom actions:
```suggestion
Follow these steps to learn how to create and use your own custom actions:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +The first step to create a custom action with Beagle Flutter, is to define the identifier. Here, let's name it `custom:log`.
```suggestion
You have to define the identifier. Here, let's name it `custom:log`.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +Now create your action regardless of Beagle. For this example, we'll use the simple function below:
```suggestion
Create your action regardless Beagle. For this example we used a simple function, see below:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +With the function and action identifier done, it's time to create the struct that we'll pass to Beagle:
```suggestion
Create the struct that it will pass to Beagle:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/actions.md
> +To Beagle be able to trigger your action, pass the map you just created through the Beagle init method:
```suggestion
Beagle needs to be able to trigger your action, you have to pass the map you created through the Beagle init method:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/components.md
> +  You will find here information of how to create and use your own components in Beagle Flutter.
```suggestion
  In this section, you will find information on how to create and use your own components in Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/components.md
> +It's pretty simple to create a custom component in Beagle Flutter, you just need to declare a map that follows the strcut `Map<String, ComponentBuilder>` and pass it to the initialization method `Bea
```suggestion
You need to declare a map that follows the struct `Map<String, ComponentBuilder>` and pass it to the initialization method `BeagleSdk.init`. 
This struct tells Beagle which widget to render when a given identifier comes into the JSON.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/components.md
> +The ComponentBuilder value of the map is a function that receives a `BeagleUIElement`, a list of a widgets and a `BeagleView` as parameters and returns a widget, following the strcut `Widget Function
```suggestion
The ComponentBuilder value of the map is a function that receives:
- A `BeagleUIElement`;
- A list of widgets;
- A `BeagleView` as parameters and it returns a widget following the struct `Widget Function(BeagleUIElement element, List<Widget> children, BeagleView view)`. 
These parameters are available because they provide all the information needed to build a custom widget, such as context and children.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/components.md
> +Follow this steps to learn how to create and use your own custom widgets:
```suggestion
Follow these steps to learn how to create and use your own custom widgets:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/components.md
> +The first step to create a custom component with Beagle Flutter, is to define the identifier. Here, let's name it `custom:loading`.
```suggestion
Define the identifier, here let's name it `custom:loading`.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/components.md
> +Now create your widget regardless of Beagle. For this example, we'll use the simple widget below:
```suggestion
Create your widget regardless of Beagle. For this example, we'll use the simple widget below:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/components.md
> +With the widget and widget identifier done, it's time to create the struct that we'll pass to Beagle:
```suggestion
Create the struct that it will pass to Beagle, see below:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/components.md
> +To Beagle be able to render your widget, pass the map you just created through the Beagle init method:
```suggestion
Pass the map you have created through the Beagle init method, now Beagle will be able to render your widget:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/operations.md
> +  You will find here information of how to create and use your own operations in Beagle Flutter.
```suggestion
 In this section, you will find information on how to create and use your own operations in Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/customization/overview.md
> +  You will find here the information on how to customize components, actions and operations in Beagle Flutter.
```suggestion
 In this section, you will find information on how to customize components, actions, and operations in Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/design-system.md
> +  You will find here information of how to create and use your own design system in Flutter.
```suggestion
 In this section, you will find information on how to create and use your own design system in Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/design-system.md
> +To be able to use images and styled texts and buttons, you must provide a implementation of DesignSystem to Beagle Flutter. You can use it in any default widget. To learn more about how to use the de
```suggestion
If you want to be able to use images, styled texts, and buttons, you must provide a DesignSystem implementation to Beagle Flutter. You can use it in any default widget. For more information about how to use the default components library, see the [configuration page]({{< ref path="/resources/customization/beagle-for-flutter/configuration" lang="en" >}}).
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/design-system.md
> +It's quite simple create your own Design System. You just need to create a class that implements the `BeagleDesignSystem` contract and provide images and styles to each method. We'll detail each one
```suggestion
It's simple to create your own Design System. You just need to:
1. Create a class that implements the `BeagleDesignSystem` contract;
2. Provide images and styles for each method. 

See more details of each one of them below:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/design-system.md
> +This method has the notation `String image(String id)`. It receives the image id that comes from JSON and returns the corresponding local image asset name. See the example:
```suggestion
This method has the notation `String image(String id)`. It receives the image id that comes from the JSON and returns the corresponding local image asset name. See the example:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/design-system.md
> +This method has the notation `BeagleButtonStyle buttonStyle(String id)`. It receives the button style id that comes from JSON and returns the `BeagleButtonStyle` corresponding. See below:
```suggestion
This method has the notation `BeagleButtonStyle buttonStyle(String id)`. It receives the button style id that comes from the JSON and returns the corresponding `BeagleButtonStyle`. See below:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/design-system.md
> +This method has the notation `TextStyle textStyle(String id)`. It receives the text style id that comes from JSON and returns the `TextStyle` corresponding. Here is an implementation:
```suggestion
This method has the notation `TextStyle textStyle(String id)`. It receives the text style id that comes from the JSON and returns the corresponding `TextStyle`. Check out an implementation:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/design-system.md
> +Just like any other configuration in Beagle Flutter, to be able to use your implementation of a Design System you need to pass it in the initialization method `BeagleSdk.init`. See below:
```suggestion
Just like any other configuration on Beagle Flutter,  if you want to use your implementation of a Design System, you need to pass it in the initialization method `BeagleSdk.init`. See below:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/development.md
> +  You will find here information of how the development of the Beagle Flutter is going.
```suggestion
 In this section, you will find information on how Beagle Flutter's developement is going.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/development.md
> +Almost done. Renderization, context, custom components and custom actions all work! Only the layout engine which is based on flexbox is partially applied. The styling is not implemented either.
```suggestion
The core features are almost done, see below what is already working:
- Renderization;
- Context;
- Custom components
- Custom actions. 
The layout engine is based on flexbox and it is partially applied. The styling is not implemented either.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/localhost.md
> +  You will find here information of how to refer to the localhost in Beagle Flutter.
```suggestion
  In this section, you will find information on how to refer to the localhost on Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/localhost.md
> +Open `ios/{project_name}/info.plist` and make sure the configuration for `NSAppTransportSecurity` is the following:
```suggestion
1. Open `ios/{project_name}/info.plist` 
2. Make sure the configuration for `NSAppTransportSecurity` is the following one:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/localhost.md
> +Another attention point of running your backend in the localhost is that while iOS does work with the address `localhost`, Android emulator doesn't. On Android emulator, to access the localhost, you
```suggestion
When running your backend in the localhost, on iOS works with the address `localhost`, however the Android emulator does not. 
To access the localhost in the Android emulator, you need to use the **IP `10.0.2.2`.** To solve this problem, you can use Flutter's `Platform` to decide what address to use. See the example below:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/_index.md
> +  You will find here information of how to configure and use services in Beagle Flutter.
```suggestion
In this section, you will find information on how to configure and use services in Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/http-client.md
> +  You will find here information of how to configure and use the HTTP client in Beagle Flutter.
```suggestion
In this section, you will information on how to configure and use the HTTP client in Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/image-downloader.md
> +  You will find here information of how to use and configure the Image Downloader in Beagle Flutter.
```suggestion
 In this section, you will information on how to use and configure the Image Downloader in Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/image-downloader.md
> +The `downloadImage` method takes as parameter the image url and returns a `Future<Uint8List>` as the representation of the downloaded image.
```suggestion
The `downloadImage` method takes as a parameter the image url and returns a `Future<Uint8List>` as the representation of the downloaded image.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/image-downloader.md
> +To create your own image downloader, you only need to implement the `downloadImage` method, here is a simplified version of the default implementation:
```suggestion
To create your own image downloader, you need to implement the `downloadImage` method, see a simplified version of the default implementation:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/image-downloader.md
> +It is worth mentioning that the default implementation of Image Downloader uses the default implementation of the HTTP client.
```suggestion
The default implementation of Image Downloader uses the same default implementation of the HTTP client.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/logger.md
> +  You will find here information of how to use the Logger in Beagle Flutter.
```suggestion
In this section, you will information on how to use the Logger in Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/logger.md
> +API for sending log output. Beagle Flutter provides a default implementation called `DefaultEmptyLogger` that doesn't log any information. Here is the contract:
```suggestion
Logger is an API that sends log output. Beagle Flutter provides a default implementation called `DefaultEmptyLogger` that doesn't log any information. Check out the contract:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/storage.md
> +  You will find here information of how to configure the storage in Beagle Flutter.
```suggestion
 In this section, you will information on how to configure the storage in Beagle Flutter.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/storage.md
> +To avoid vulnerability issues, the default implementation stores information only in memory.
```suggestion
To avoid vulnerability issues, the default implementation stores information only in the memory.
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-flutter/services/storage.md
> +To create your own storage, you only need to create a class that implements the `Storage` abstract class, here is the default implementation:
```suggestion
Create a class that implements the `Storage` abstract class, here is the default implementation:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/en/resources/customization/beagle-for-web/advanced-topics/data-structure.md
> +It is recommended that the back-end always returns a JSON representing a tree of components, as it is expected by Beagle. If this is not possible, Beagle Web makes it possible to pre-process the resp
```suggestion
The back-end should always return a JSON representing a tree of components, as it is expected by Beagle. If this is not possible, Beagle Web will make it possible to pre-process the response and build the tree in the front-end before Beagle actually works upon it, like in [**lifecycles**]({{< ref path="/resources/customization/beagle-for-web/advanced-topics/lifecycles" lang="en" >}}).
```

2021-07-16 15:54 UTC, jessica-tw commented on content/pt/api/context/global-context.md
> +No Flutter o Contexto Global pode ser chamado através da função `getInstance()` que vai prover uma instancia unica(Singleton) do `GlobalContext`, abaixo segue um exemplo de como utilizar:
```suggestion
No Flutter o Contexto Global pode ser chamado por meio da função `getInstance()`, ela provê uma instância única(Singleton) do `GlobalContext`, veja abaixo um exemplo de como utilizar:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/pt/api/context/global-context.md
> +Assim como no método set será necessário chamar a função `getInstance()` do `GlobalContext` para utilizar o `get` do contexto global, como no exemplo abaixo:
```suggestion
Assim como no método set é necessário chamar a função `getInstance()` do `GlobalContext`, você precisa utilizar o `get` do contexto global, veja o exemplo abaixo:
```

2021-07-16 15:54 UTC, jessica-tw commented on content/pt/api/context/global-context.md
> +Lembre-se que no Flutter o acesso ao contexto global é feito através do `getInstance()`
```suggestion
Lembre-se que no Flutter o acesso ao contexto global é feito por meio do `getInstance()`
```

2021-07-19 13:33 UTC, matheusribeirozup commented on content/en/get-started/using-beagle/flutter.md
> +- [Design system]({{< ref path="/resources/customization/beagle-for-flutter/design-system" lang="en" >}}): register local images (mobileId) and styles for your components.
It's the JSON attribute that is used only in mobile application. I'll describe it more.

2021-07-19 15:01 UTC, matheusribeirozup commented on content/en/api/context/global-context.md
> +Remember that in the Flutter the global context access is made over the `getInstance()`
Here I just follow the pattern used in other tabs using "Remember that"

2021-07-20 14:33 UTC, carlossteinzup approved these changes

2021-07-20 14:33 UTC, merged