fix: Update docs 2.0
ZupIT/beagle-docs pull request #858
Opened 2022-03-04 18:18 UTC by carlossteinzup

2022-03-04 20:01 UTC, hectorcustodiozup requested changes

2022-03-04 20:01 UTC, hectorcustodiozup commented on content/pt/api/components/widget.md
> +O Widget é uma classe abstrata que permite que um componente visual seja referenciado no Beagle. Quando um componente visual estende da classe `widget`, ele herda 3 propriedades que habilitam algum a
Are there beagle components which are not visual? if so, ignore the changes

2022-03-04 20:01 UTC, hectorcustodiozup commented on content/pt/api/components/widget.md
> +| id        | ​String |      | identifica o componente visual que o widget referencia |
```suggestion
| id        | ​String |      | identifica o componente que o widget referencia |
```

2022-03-04 20:01 UTC, hectorcustodiozup commented on content/pt/api/components/widget.md
> +| style | ​[Style]({{< ref path="/api/style/overview.md" lang="pt" >}})​ | | define uma série de propriedades visuais. |
```suggestion
| style | ​[Style]({{< ref path="/api/style/overview.md" lang="pt" >}})​ | | define uma série de propriedades de estilo. |
```

2022-03-04 20:01 UTC, hectorcustodiozup commented on content/pt/api/components/widget.md
> +        "text" : "I'am a Server-Driven text"
```suggestion
        "text" : "I am a Server-Driven text"
```

2022-03-04 20:01 UTC, hectorcustodiozup commented on content/pt/api/components/widget.md
> +        "text" : "I'am another Server-Driven text"
```suggestion
        "text" : "I am another Server-Driven text"
```

2022-03-04 20:10 UTC, carlossteinzup commented on content/en/api/actions/navigate/pushview.md
> +  It is important to explain how the ``Route`` property works. It receives the endpoint of a new screen or server driven component. When this is done, a JSON with the screen or component is obtained
It is too... Since it gets the request info, it wraps the content received, so it accepts the component code. The example did not list an endpoint...but a component...só I found it important to make sure people got what is happening since it was not explained before. It was just made like that... In the description, it says that the Route will accept an URL parameter but in the example code, it lists a component.

2022-03-04 20:13 UTC, carlossteinzup commented on content/en/api/actions/navigate/resetapplication.md
> +This action creates a new canvas in a new stack and destroys all previous stacks.
```suggestion
This action creates a new screen in a new stack and destroys all previous stacks.
```

2022-03-04 20:14 UTC, carlossteinzup commented on content/en/api/actions/navigate/resetapplication.md
> +This action creates a new canvas in a new stack and destroys all previous stacks.
It is a screen. I changed that now

2022-03-04 20:21 UTC, carlossteinzup commented on content/en/api/actions/navigate/poptoview.md
> +  The examples below require you to create these screens on a local backend. However, it is possible to test them without a Backend. To do this, you just need to get the JSONS from the screens listed
I will update this in the next PR.

2022-03-04 20:26 UTC, carlossteinzup commented on content/en/api/actions/navigate/resetstack.md
> +{{% playground file="pushStack.json" language="en" %}}
```suggestion
{{% playground file="resetStack.json" language="en" %}}
```

2022-03-04 20:28 UTC, carlossteinzup commented on content/en/api/actions/navigate/resetstack.md
> +{{% playground file="pushStack.json" language="en" %}}
Solved. The name was wrong. It should be reset stack. It is not necessary to add files to playground. It gets them from the code.

2022-03-04 20:33 UTC, carlossteinzup commented on content/pt/api/components/widget.md
> +| id        | ​String |      | identifica o componente visual que o widget referencia |
```suggestion
| id        | ​String |      | identifica o componente do Beagle que o widget referencia |
```

2022-03-04 20:34 UTC, carlossteinzup commented on content/pt/api/actions/navigate/resetstack.md
> +{{% playground file="pushStack.json" language="pt" %}}
```suggestion
{{% playground file="resetStack.json" language="pt" %}}
```

2022-03-04 20:35 UTC, carlossteinzup commented on content/en/api/components/widget.md
> +| id | String | | identifies the visual component that the widget references |
```suggestion
| id | String | | identifies the Beagle components that the widget references |
```

2022-03-04 20:47 UTC, carlossteinzup commented on content/pt/api/actions/navigate/resetapplication.md
> +{{% playground file="pushStack.json" language="pt" %}}
```suggestion
{{% playground file="resetApplication.json" language="pt" %}}
```

2022-03-04 20:48 UTC, carlossteinzup commented on content/pt/api/actions/navigate/resetapplication.md
> +{{% playground file="pushStack.json" language="pt" %}}
```suggestion
{{% playground file="resetApplication.json" language="pt" %}}
```

2022-03-04 20:52 UTC, carlossteinzup commented on content/pt/api/actions/navigate/resetapplication.md
> +{{% playground file="pushStack.json" language="pt" %}}
```suggestion
{{% playground file="resetApplication.json" language="pt" %}}
```

2022-03-07 12:35 UTC, hectorcustodiozup approved these changes

2022-03-07 12:36 UTC, merged