Translate docs 2.0
ZupIT/beagle-docs pull request #868
Opened 2022-03-08 19:40 UTC by carlossteinzup

2022-03-09 18:50 UTC, hectorcustodiozup requested changes

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/android/customization/view-client.md
> +The ViewClient interface has to functions **`fetch`** and **`prefetch`**.
```suggestion
The ViewClient interface has two functions **`fetch`** and **`prefetch`**.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/android/customization/view-client.md
> +1. It searches for a response data in a local cache, and if a cache exists, this function removes it from cache and return its contents;
Is it removed from the cache or only retrieved?

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/android/customization/view-client.md
> +2. If there is no response data in cache, this function calls the `HttpClient` and make a request for a ResponseData.
```suggestion
2. If there is no response data in cache, this function calls the `HttpClient` and makes a request which returns a ResponseData.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/android/customization/view-client.md
> +The **`prefech`** default implementation has 2 functionalities:
```suggestion
The **`prefetch`** default implementation has 2 functionalities:
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/android/customization/view-client.md
> +2. If there is no response data in cache, this function calls the `HttpClient` and make the request for a ResponseData and store it in cache (memory).
Both fetch and preFetch seem to be very similar in definition. Is that so? Do both of them work with the cache storage?

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/android/customization/view-client.md
> +Above we have implemented a logic to `fetch` and `prefetch` that will store every fetch result in memory using a MutableMap called `cachedResponses`. It uses the *request url* as key, and search for
```suggestion
Above we have implemented a logic to `fetch` and `prefetch` that will store every fetch result in memory using a MutableMap called `cachedResponses`. It uses the *request url* as key, and searches for a ``ResponseData`` in it every time `fetch` or `prefetch` is called. This is a simple implementation, since this cache would never expire, and the objective here is to show how this feature could be implemented using the ViewClient.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/ios/customization/dependencies/overview.md
> +It is a protocol that can be implemented to track the screen appearance, actions and click events.
```suggestion
It is a protocol that can be implemented to track the appearance of the screen, actions and click events.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/ios/customization/dependencies/overview.md
> +It exposes an custom navigation controller registration methods and a [**navigation animation**]({{< ref path="/ios/customization/navigation-animation" lang="en" >}}).
```suggestion
It exposes a custom navigation controller registration methods and a [**navigation animation**]({{< ref path="/ios/customization/navigation-animation" lang="en" >}}).
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/ios/customization/dependencies/overview.md
> +It is responsible for providing context operations, it exposes the `register` function so that it is possible to register custom operations in Beagle's default OperationsProvider.
```suggestion
It is responsible for providing context operations, exposing the `register` function so that it is possible to register custom operations in Beagle's default OperationsProvider.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/web/commons/navigation/navigation-controllers.md
> +You can ignore this if you don't intent to show a Beagle UI before the success event.
```suggestion
You can ignore this if you don't intend to present a Beagle UI before the success event.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/web/commons/navigation/navigation-controllers.md
> +If you have three navigation controllers: `inYourFace`, `secured` and `public`. `inYourFace` is the default, while `secured` and `public` are used in specific sections of the app and are referenced v
Is inYourFace a custom name?

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/en/web/commons/view-client.md
> +It does nothing more than this, and this might be enough for most applications. But, some applications may need extra behavior when fetching views, and this is the place where it should be customized
```suggestion
It does nothing other than this, and this might be enough for most applications. But, some applications may need extra behavior when fetching views, and this is the place where it should be customized.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/android/customization/view-client.md
> +1. Ela procura um **`response data`** em um cache local, e caso exista, esta função o remove do cache e retorna seu conteúdo;
Same as the english version

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/ios/customization/dependencies/overview.md
> +É importante que se faça essa *configuração* das dependencias durante o processo de inicialização do aplicativo, ou seja, na função `AppDelegate` `didFinishLaunchingWithOptions` conforme mostrado aba
```suggestion
É importante que se faça essa *configuração* das dependências durante o processo de inicialização da aplicação, ou seja, na função `AppDelegate` `didFinishLaunchingWithOptions` conforme mostrado abaixo:
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/ios/customization/dependencies/overview.md
> +Este wrapper de propriedade gera um `fatalError` se for usado para resolver uma dependência que não seja Beagles' ou que seja opcional e não tenha sido configurada, por exemplo:(logger, analyticsProv
```suggestion
Este wrapper de propriedade gera um `fatalError` se for usado para resolver uma dependência que não sejado Beagle ou que seja opcional e não tenha sido configurada, por exemplo:(logger, analyticsProvider, deepLinkHandler, networkClient), para contornar isso, basta usar `@OptionalInjected` que retornará nil se a dependência não for resolvida, conforme mostrado abaixo.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/ios/customization/dependencies/overview.md
> +Alguns widgets possuem uma variável que permite definir o estilo. O nome de cada um deve ser passado para a dependência **Tema**, para que esse estilo possa ser utilizado em seu respectivo componente
```suggestion
Alguns widgets possuem uma variável que permite definir o estilo. O nome de cada um deve ser passado para a dependência **Theme**, para que esse estilo possa ser utilizado em seu respectivo componente.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/ios/customization/dependencies/overview.md
> +Você usará `Text` como um widget que tem `UITextView` como sua **visualização UIKit**. Depois disso, você aplicará suas alterações de estilo a esta visualização, que também terá as personalizações `f
```suggestion
Você usará `Text` como um widget que tem `UITextView` como sua **UIKit view**. Depois disso, você aplicará suas alterações de estilo a esta visualização, que também terá as personalizações `font` e `textColor`.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/ios/customization/dependencies/overview.md
> +**Passo 3**: adicione a dependência de tema personalizado às dependências do Beagles
```suggestion
**Passo 3**: adicione a dependência de tema personalizado às dependências do Beagle
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/ios/customization/dependencies/overview.md
> +É um protocolo que pode ser implementado para rastrear a aparência da tela, ações e eventos de clique.
```suggestion
É um protocolo que pode ser implementado para rastrear carregamentos de tela, ações e eventos de clique em componentes Beagle.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/ios/customization/dependencies/overview.md
> +Ele expõe métodos de registro de um controlador de navegação personalizado e uma [** animação de navegação**]({{< ref path="/ios/customization/navigation-animation" lang="en" >}}).
I think that the words which are related to the framework can be kept without translation. e.g: Navigation Controller

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/ios/customization/dependencies/view-client.md
> +Para implementar um ViewClient customizado, podemos adotar como base o `ViewClient` padrão do Beagle. Dessa forma, definimos 3 dependencias base que serão ultilizadas por nossa implementação:
```suggestion
Para implementar um ViewClient customizado, podemos adotar como base o `ViewClient` padrão do Beagle. Dessa forma, definimos 3 dependências base que serão utilizadas por nossa implementação:
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/ios/customization/dependencies/view-client.md
> +Além disso podemos definir uma *quarta dependencia* que será responsável pelo gerenciamento de cache dos componentes, para esse exemplo a nomearemos de `CacheManager`.
```suggestion
Além disso podemos definir uma *quarta dependência* que será responsável pelo gerenciamento de cache dos componentes, para esse exemplo a nomearemos de `CacheManager`.
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/web/commons/beagle-remote-view.md
> +description: Descrição do BeagleRemoteView e seus parametros
```suggestion
description: Descrição do BeagleRemoteView e seus parâmetros
```

2022-03-09 18:50 UTC, hectorcustodiozup commented on content/pt/web/commons/view-client.md
> +2. Quando a resposta chega do HttpClient, ele verifica se a propriedade de navegação `preFetch` é ``verdadeira`` (``true``) e, *de ​​forma assíncrona*, faz uma busca prévia de seus resultados.
```suggestion
2. Quando a resposta chega do HttpClient, ele verifica se a propriedade de navegação `preFetch` tem o valor igual a ``true`` e, *de ​​forma assíncrona*, faz uma busca prévia de seus resultados.
```

2022-03-09 19:24 UTC, carlossteinzup commented on content/en/android/customization/view-client.md
> +1. It searches for a response data in a local cache, and if a cache exists, this function removes it from cache and return its contents;
The previous description says it is removed but in a different way.

2022-03-09 19:29 UTC, carlossteinzup commented on content/en/android/customization/view-client.md
> +2. If there is no response data in cache, this function calls the `HttpClient` and make the request for a ResponseData and store it in cache (memory).
Yes. Both could handle cache

2022-03-09 19:35 UTC, carlossteinzup commented on content/pt/ios/customization/dependencies/overview.md
> +Ele expõe métodos de registro de um controlador de navegação personalizado e uma [** animação de navegação**]({{< ref path="/ios/customization/navigation-animation" lang="en" >}}).
```suggestion
Ele expõe métodos de registro de um `navigation controler` personalizado e uma [** animação de navegação**]({{< ref path="/ios/customization/navigation-animation" lang="en" >}}).
```

2022-03-09 19:43 UTC, carlossteinzup commented on content/en/web/commons/navigation/navigation-controllers.md
> +If you have three navigation controllers: `inYourFace`, `secured` and `public`. `inYourFace` is the default, while `secured` and `public` are used in specific sections of the app and are referenced v
Yes

2022-03-10 12:56 UTC, hectorcustodiozup approved these changes

2022-03-10 13:07 UTC, merged